using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Repository.Migrations
{
    /// <inheritdoc />
    public partial class Mig_1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    CountryName = table.Column<string>(type: "text", nullable: false),
                    isDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: false),
                    Password = table.Column<string>(type: "text", nullable: false),
                    RefreshToken = table.Column<string>(type: "text", nullable: true),
                    RefreshTokenExpireDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    Role = table.Column<int>(type: "integer", nullable: false),
                    isDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Districts",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    DistrictName = table.Column<string>(type: "text", nullable: false),
                    CountryId = table.Column<long>(type: "bigint", nullable: false),
                    isDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Districts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Districts_Countries_CountryId",
                        column: x => x.CountryId,
                        principalTable: "Countries",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "Estates",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FieldM2 = table.Column<long>(type: "bigint", nullable: false),
                    BuildingAge = table.Column<int>(type: "integer", nullable: false),
                    EstateType = table.Column<int>(type: "integer", nullable: false),
                    RentType = table.Column<int>(type: "integer", nullable: false),
                    Dsc = table.Column<string>(type: "text", nullable: true),
                    Price = table.Column<decimal>(type: "numeric", nullable: false),
                    HeaderDsc = table.Column<string>(type: "text", nullable: false),
                    DistrictId = table.Column<long>(type: "bigint", nullable: false),
                    isDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Estates", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Estates_Districts_DistrictId",
                        column: x => x.DistrictId,
                        principalTable: "Districts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "CountryName", "CreatedDate", "UpdatedDate", "isDeleted" },
                values: new object[,]
                {
                    { 1L, "Adana", null, null, false },
                    { 2L, "Adiyaman", null, null, false },
                    { 3L, "Afyon", null, null, false },
                    { 4L, "Ağri", null, null, false },
                    { 5L, "Amasya", null, null, false },
                    { 6L, "Ankara", null, null, false },
                    { 7L, "Antalya", null, null, false },
                    { 8L, "Artvin", null, null, false },
                    { 9L, "Aydin", null, null, false },
                    { 10L, "Balikesir", null, null, false },
                    { 11L, "Bilecik", null, null, false },
                    { 12L, "Bingöl", null, null, false },
                    { 13L, "Bitlis", null, null, false },
                    { 14L, "Bolu", null, null, false },
                    { 15L, "Burdur", null, null, false },
                    { 16L, "Bursa", null, null, false },
                    { 17L, "Çanakkale", null, null, false },
                    { 18L, "Çankiri", null, null, false },
                    { 19L, "Çorum", null, null, false },
                    { 20L, "Denizlİ", null, null, false },
                    { 21L, "Diyarbakir", null, null, false },
                    { 22L, "Edirne", null, null, false },
                    { 23L, "Elaziğ", null, null, false },
                    { 24L, "Erzincan", null, null, false },
                    { 25L, "Erzurum", null, null, false },
                    { 26L, "Eskişehir", null, null, false },
                    { 27L, "Gaziantep", null, null, false },
                    { 28L, "Giresun", null, null, false },
                    { 29L, "Gümüşhane", null, null, false },
                    { 30L, "Hakkari", null, null, false },
                    { 31L, "Hatay", null, null, false },
                    { 32L, "Isparta", null, null, false },
                    { 33L, "İçel", null, null, false },
                    { 34L, "İstanbul", null, null, false },
                    { 35L, "İzmir", null, null, false },
                    { 36L, "Kars", null, null, false },
                    { 37L, "Kastamonu", null, null, false },
                    { 38L, "Kayserİ", null, null, false },
                    { 39L, "Kirklareli", null, null, false },
                    { 40L, "Kirşehir", null, null, false },
                    { 41L, "Kocaeli", null, null, false },
                    { 42L, "Konya", null, null, false },
                    { 43L, "Kütahya", null, null, false },
                    { 44L, "Malatya", null, null, false },
                    { 45L, "Manisa", null, null, false },
                    { 46L, "Kahramanmaraş", null, null, false },
                    { 47L, "Mardin", null, null, false },
                    { 48L, "Muğla", null, null, false },
                    { 49L, "Muş", null, null, false },
                    { 50L, "Nevşehir", null, null, false },
                    { 51L, "Niğde", null, null, false },
                    { 52L, "Ordu", null, null, false },
                    { 53L, "Rize", null, null, false },
                    { 54L, "Sakarya", null, null, false },
                    { 55L, "Samsun", null, null, false },
                    { 56L, "Siirt", null, null, false },
                    { 57L, "Sinop", null, null, false },
                    { 58L, "Sivas", null, null, false },
                    { 59L, "Tekirdağ", null, null, false },
                    { 60L, "Tokat", null, null, false },
                    { 61L, "Trabzon", null, null, false },
                    { 62L, "Tuncelİ", null, null, false },
                    { 63L, "Şanliurfa", null, null, false },
                    { 64L, "Uşak", null, null, false },
                    { 65L, "Van", null, null, false },
                    { 66L, "Yozgat", null, null, false },
                    { 67L, "Zonguldak", null, null, false },
                    { 68L, "Aksaray", null, null, false },
                    { 69L, "Bayburt", null, null, false },
                    { 70L, "Karaman", null, null, false },
                    { 71L, "Kirikkale", null, null, false },
                    { 72L, "Batman", null, null, false },
                    { 73L, "Şirnak", null, null, false },
                    { 74L, "Bartin", null, null, false },
                    { 75L, "Ardahan", null, null, false },
                    { 76L, "Iğdir", null, null, false },
                    { 77L, "Yalova", null, null, false },
                    { 78L, "Karabük", null, null, false },
                    { 79L, "Kilis", null, null, false },
                    { 80L, "Osmaniye", null, null, false },
                    { 81L, "Düzce", null, null, false }
                });

            migrationBuilder.InsertData(
                table: "Districts",
                columns: new[] { "Id", "CountryId", "CreatedDate", "DistrictName", "UpdatedDate", "isDeleted" },
                values: new object[,]
                {
                    { 1L, 1L, null, "Merkez", null, false },
                    { 2L, 1L, null, "Aladag", null, false },
                    { 3L, 1L, null, "Ceyhan", null, false },
                    { 4L, 1L, null, "Feke", null, false },
                    { 5L, 1L, null, "Imamoglu", null, false },
                    { 6L, 1L, null, "Karaisali", null, false },
                    { 7L, 1L, null, "Karatas", null, false },
                    { 8L, 1L, null, "Kozan", null, false },
                    { 9L, 1L, null, "Pozanti", null, false },
                    { 10L, 1L, null, "Saimbeyli", null, false },
                    { 11L, 1L, null, "Seyhan", null, false },
                    { 12L, 1L, null, "Tufanbeyli", null, false },
                    { 13L, 1L, null, "Yumurtalik", null, false },
                    { 14L, 1L, null, "Yüregir", null, false },
                    { 15L, 2L, null, "Merkez", null, false },
                    { 16L, 2L, null, "Besni", null, false },
                    { 17L, 2L, null, "Çelikhan", null, false },
                    { 18L, 2L, null, "Gerger", null, false },
                    { 19L, 2L, null, "Gölbasi", null, false },
                    { 20L, 2L, null, "Kahta", null, false },
                    { 21L, 2L, null, "Samsat", null, false },
                    { 22L, 2L, null, "Sincik", null, false },
                    { 23L, 2L, null, "Tut", null, false },
                    { 24L, 3L, null, "Merkez", null, false },
                    { 25L, 3L, null, "Basmakçi", null, false },
                    { 26L, 3L, null, "Bayat", null, false },
                    { 27L, 3L, null, "Bolvadin", null, false },
                    { 28L, 3L, null, "Çobanlar", null, false },
                    { 29L, 3L, null, "Çay", null, false },
                    { 30L, 3L, null, "Dazkiri", null, false },
                    { 31L, 3L, null, "Dinar", null, false },
                    { 32L, 3L, null, "Emirdag", null, false },
                    { 33L, 3L, null, "Evciler", null, false },
                    { 34L, 3L, null, "Hocalar", null, false },
                    { 35L, 3L, null, "Ihsaniye", null, false },
                    { 36L, 3L, null, "Iscehisar", null, false },
                    { 37L, 3L, null, "Kizilören", null, false },
                    { 38L, 3L, null, "Sandikli", null, false },
                    { 39L, 3L, null, "Sincanli", null, false },
                    { 40L, 3L, null, "Sultandagi", null, false },
                    { 41L, 3L, null, "Suhut", null, false },
                    { 42L, 4L, null, "Merkez", null, false },
                    { 43L, 4L, null, "Diyadin", null, false },
                    { 44L, 4L, null, "Dogubeyazit", null, false },
                    { 45L, 4L, null, "Eleskirt", null, false },
                    { 46L, 4L, null, "Hamur", null, false },
                    { 47L, 4L, null, "Patnos", null, false },
                    { 48L, 4L, null, "Tasliçay", null, false },
                    { 49L, 4L, null, "Tutak", null, false },
                    { 50L, 5L, null, "Merkez", null, false },
                    { 51L, 5L, null, "Göynücek", null, false },
                    { 52L, 5L, null, "Gümüshacikö", null, false },
                    { 53L, 5L, null, "Hamamözü", null, false },
                    { 54L, 5L, null, "Merzifon", null, false },
                    { 55L, 5L, null, "Suluova", null, false },
                    { 56L, 5L, null, "Tasova", null, false },
                    { 57L, 6L, null, "Merkez", null, false },
                    { 58L, 6L, null, "Akyurt", null, false },
                    { 59L, 6L, null, "Altindag", null, false },
                    { 60L, 6L, null, "Ayas", null, false },
                    { 61L, 6L, null, "Bala", null, false },
                    { 62L, 6L, null, "Beypazari", null, false },
                    { 63L, 6L, null, "Çamlidere", null, false },
                    { 64L, 6L, null, "Çankaya", null, false },
                    { 65L, 6L, null, "Çubuk", null, false },
                    { 66L, 6L, null, "Elmadag", null, false },
                    { 67L, 6L, null, "Etimesgut", null, false },
                    { 68L, 6L, null, "Evren", null, false },
                    { 69L, 6L, null, "Gölbasi", null, false },
                    { 70L, 6L, null, "Güdül", null, false },
                    { 71L, 6L, null, "Haymana", null, false },
                    { 72L, 6L, null, "Kalecik", null, false },
                    { 73L, 6L, null, "Kazan", null, false },
                    { 74L, 6L, null, "Keçiören", null, false },
                    { 75L, 6L, null, "Kizilcahama", null, false },
                    { 76L, 6L, null, "Mamak", null, false },
                    { 77L, 6L, null, "Nallihan", null, false },
                    { 78L, 6L, null, "Polatli", null, false },
                    { 79L, 6L, null, "Sincan", null, false },
                    { 80L, 6L, null, "Sereflikoçh", null, false },
                    { 81L, 6L, null, "Yenimahalle", null, false },
                    { 82L, 7L, null, "Merkez", null, false },
                    { 83L, 7L, null, "Akseki", null, false },
                    { 84L, 7L, null, "Alanya", null, false },
                    { 85L, 7L, null, "Demre", null, false },
                    { 86L, 7L, null, "Elmali", null, false },
                    { 87L, 7L, null, "Finike", null, false },
                    { 88L, 7L, null, "Gazipasa", null, false },
                    { 89L, 7L, null, "Gündogmus", null, false },
                    { 90L, 7L, null, "Ibradi", null, false },
                    { 91L, 7L, null, "Kale", null, false },
                    { 92L, 7L, null, "Kas", null, false },
                    { 93L, 7L, null, "Kemer", null, false },
                    { 94L, 7L, null, "Korkuteli", null, false },
                    { 95L, 7L, null, "Kumluca", null, false },
                    { 96L, 7L, null, "Manavgat", null, false },
                    { 97L, 7L, null, "Serik", null, false },
                    { 98L, 8L, null, "Merkez", null, false },
                    { 99L, 8L, null, "Ardanuç", null, false },
                    { 100L, 8L, null, "Arhavi", null, false },
                    { 101L, 8L, null, "Borçka", null, false },
                    { 102L, 8L, null, "Hopa", null, false },
                    { 103L, 8L, null, "Murgul", null, false },
                    { 104L, 8L, null, "Savsat", null, false },
                    { 105L, 8L, null, "Yusufeli", null, false },
                    { 106L, 9L, null, "Merkez", null, false },
                    { 107L, 9L, null, "Bozdogan", null, false },
                    { 108L, 9L, null, "Buharkent", null, false },
                    { 109L, 9L, null, "Çine", null, false },
                    { 110L, 9L, null, "Germencik", null, false },
                    { 111L, 9L, null, "Incirliova", null, false },
                    { 112L, 9L, null, "Karacasu", null, false },
                    { 113L, 9L, null, "Karpuzlu", null, false },
                    { 114L, 9L, null, "Koçarli", null, false },
                    { 115L, 9L, null, "Kösk", null, false },
                    { 116L, 9L, null, "Kusadasi", null, false },
                    { 117L, 9L, null, "Kuyucak", null, false },
                    { 118L, 9L, null, "Nazilli", null, false },
                    { 119L, 9L, null, "Söke", null, false },
                    { 120L, 9L, null, "Sultanhisar", null, false },
                    { 121L, 9L, null, "Yenihisar", null, false },
                    { 122L, 9L, null, "Yenipazar", null, false },
                    { 123L, 10L, null, "Merkez", null, false },
                    { 124L, 10L, null, "Ayvalik", null, false },
                    { 125L, 10L, null, "Akçay", null, false },
                    { 126L, 10L, null, "Balya", null, false },
                    { 127L, 10L, null, "Bandirma", null, false },
                    { 128L, 10L, null, "Bigadiç", null, false },
                    { 129L, 10L, null, "Burhaniye", null, false },
                    { 130L, 10L, null, "Dursunbey", null, false },
                    { 131L, 10L, null, "Edremit", null, false },
                    { 132L, 10L, null, "Erdek", null, false },
                    { 133L, 10L, null, "Gönen", null, false },
                    { 134L, 10L, null, "Gömeç", null, false },
                    { 135L, 10L, null, "Havran", null, false },
                    { 136L, 10L, null, "Ivrindi", null, false },
                    { 137L, 10L, null, "Kepsut", null, false },
                    { 138L, 10L, null, "Manyas", null, false },
                    { 139L, 10L, null, "Marmara", null, false },
                    { 140L, 10L, null, "Savastepe", null, false },
                    { 141L, 10L, null, "Sindirgi", null, false },
                    { 142L, 10L, null, "Susurluk", null, false },
                    { 143L, 11L, null, "Merkez", null, false },
                    { 144L, 11L, null, "Bozöyük", null, false },
                    { 145L, 11L, null, "Gölpazari", null, false },
                    { 146L, 11L, null, "Inhisar", null, false },
                    { 147L, 11L, null, "Osmaneli", null, false },
                    { 148L, 11L, null, "Pazaryeri", null, false },
                    { 149L, 11L, null, "Sögüt", null, false },
                    { 150L, 11L, null, "Yenipazar", null, false },
                    { 151L, 12L, null, "Merkez", null, false },
                    { 152L, 12L, null, "Adakli", null, false },
                    { 153L, 12L, null, "Genç", null, false },
                    { 154L, 12L, null, "Karliova", null, false },
                    { 155L, 12L, null, "Kigi", null, false },
                    { 156L, 12L, null, "Solhan", null, false },
                    { 157L, 12L, null, "Yayladere", null, false },
                    { 158L, 12L, null, "Yedisu", null, false },
                    { 159L, 13L, null, "Merkez", null, false },
                    { 160L, 13L, null, "Adilcevaz", null, false },
                    { 161L, 13L, null, "Ahlat", null, false },
                    { 162L, 13L, null, "Güroymak", null, false },
                    { 163L, 13L, null, "Hizan", null, false },
                    { 164L, 13L, null, "Mutki", null, false },
                    { 165L, 13L, null, "Tatvan", null, false },
                    { 166L, 14L, null, "Merkez", null, false },
                    { 167L, 14L, null, "Dörtdivan", null, false },
                    { 168L, 14L, null, "Gerede", null, false },
                    { 169L, 14L, null, "Göynük", null, false },
                    { 170L, 14L, null, "Kibriscik", null, false },
                    { 171L, 14L, null, "Mengen", null, false },
                    { 172L, 14L, null, "Mudurnu", null, false },
                    { 173L, 14L, null, "Seben", null, false },
                    { 174L, 14L, null, "Yeniçaga", null, false },
                    { 175L, 15L, null, "Merkez", null, false },
                    { 176L, 15L, null, "Altinyayla", null, false },
                    { 177L, 15L, null, "Aglasun", null, false },
                    { 178L, 15L, null, "Bucak", null, false },
                    { 179L, 15L, null, "Çavdir", null, false },
                    { 180L, 15L, null, "Çeltikçi", null, false },
                    { 181L, 15L, null, "Gölhisar", null, false },
                    { 182L, 15L, null, "Karamanli", null, false },
                    { 183L, 15L, null, "Kemer", null, false },
                    { 184L, 15L, null, "Tefenni", null, false },
                    { 185L, 15L, null, "Yesilova", null, false },
                    { 186L, 16L, null, "Merkez", null, false },
                    { 187L, 16L, null, "Büyükorhan", null, false },
                    { 188L, 16L, null, "Gemlik", null, false },
                    { 189L, 16L, null, "Gürsu", null, false },
                    { 190L, 16L, null, "Harmancik", null, false },
                    { 191L, 16L, null, "Inegöl", null, false },
                    { 192L, 16L, null, "Iznik", null, false },
                    { 193L, 16L, null, "Karacabey", null, false },
                    { 194L, 16L, null, "Keles", null, false },
                    { 195L, 16L, null, "Kestel", null, false },
                    { 196L, 16L, null, "Mudanya", null, false },
                    { 197L, 16L, null, "Mustafakema", null, false },
                    { 198L, 16L, null, "Nilüfer", null, false },
                    { 199L, 16L, null, "Orhaneli", null, false },
                    { 200L, 16L, null, "Orhangazi", null, false },
                    { 201L, 16L, null, "Osmangazi", null, false },
                    { 202L, 16L, null, "Yenisehir", null, false },
                    { 203L, 16L, null, "Yildirim", null, false },
                    { 204L, 17L, null, "Merkez", null, false },
                    { 205L, 17L, null, "Ayvacik", null, false },
                    { 206L, 17L, null, "Bayramiç", null, false },
                    { 207L, 17L, null, "Bozcaada", null, false },
                    { 208L, 17L, null, "Biga", null, false },
                    { 209L, 17L, null, "Çan", null, false },
                    { 210L, 17L, null, "Eceabat", null, false },
                    { 211L, 17L, null, "Ezine", null, false },
                    { 212L, 17L, null, "Gelibolu", null, false },
                    { 213L, 17L, null, "Gökçeada", null, false },
                    { 214L, 17L, null, "Lapseki", null, false },
                    { 215L, 17L, null, "Yenice", null, false },
                    { 216L, 18L, null, "Merkez", null, false },
                    { 217L, 18L, null, "Atkaracalar", null, false },
                    { 218L, 18L, null, "Bayramören", null, false },
                    { 219L, 18L, null, "Çerkes", null, false },
                    { 220L, 18L, null, "Eldivan", null, false },
                    { 221L, 18L, null, "Ilgaz", null, false },
                    { 222L, 18L, null, "Kizilirmak", null, false },
                    { 223L, 18L, null, "Korgun", null, false },
                    { 224L, 18L, null, "Kursunlu", null, false },
                    { 225L, 18L, null, "Orta", null, false },
                    { 226L, 18L, null, "Ovacik", null, false },
                    { 227L, 18L, null, "Sabanözü", null, false },
                    { 228L, 18L, null, "Yaprakli", null, false },
                    { 229L, 19L, null, "Merkez", null, false },
                    { 230L, 19L, null, "Alaca", null, false },
                    { 231L, 19L, null, "Bayat", null, false },
                    { 232L, 19L, null, "Bogazkale", null, false },
                    { 233L, 19L, null, "Dodurga", null, false },
                    { 234L, 19L, null, "Iskilip", null, false },
                    { 235L, 19L, null, "Kargi", null, false },
                    { 236L, 19L, null, "Laçin", null, false },
                    { 237L, 19L, null, "Mecitözü", null, false },
                    { 238L, 19L, null, "Oguzlar", null, false },
                    { 239L, 19L, null, "Ortaköy", null, false },
                    { 240L, 19L, null, "Osmancik", null, false },
                    { 241L, 19L, null, "Sungurlu", null, false },
                    { 242L, 19L, null, "Ugurludag", null, false },
                    { 243L, 20L, null, "Merkez", null, false },
                    { 244L, 20L, null, "Acipayam", null, false },
                    { 245L, 20L, null, "Akköy", null, false },
                    { 246L, 20L, null, "Babadag", null, false },
                    { 247L, 20L, null, "Baklan", null, false },
                    { 248L, 20L, null, "Bekilli", null, false },
                    { 249L, 20L, null, "Beyagaç", null, false },
                    { 250L, 20L, null, "Buldan", null, false },
                    { 251L, 20L, null, "Bozkurt", null, false },
                    { 252L, 20L, null, "Çal", null, false },
                    { 253L, 20L, null, "Çameli", null, false },
                    { 254L, 20L, null, "Çardak", null, false },
                    { 255L, 20L, null, "Çivril", null, false },
                    { 256L, 20L, null, "Güney", null, false },
                    { 257L, 20L, null, "Honaz", null, false },
                    { 258L, 20L, null, "Kale", null, false },
                    { 259L, 20L, null, "Sarayköy", null, false },
                    { 260L, 20L, null, "Serinhisar", null, false },
                    { 261L, 20L, null, "Tavas", null, false },
                    { 262L, 21L, null, "Merkez", null, false },
                    { 263L, 21L, null, "Bismil", null, false },
                    { 264L, 21L, null, "Çermik", null, false },
                    { 265L, 21L, null, "Çinar", null, false },
                    { 266L, 21L, null, "Çüngüs", null, false },
                    { 267L, 21L, null, "Dicle", null, false },
                    { 268L, 21L, null, "Egil", null, false },
                    { 269L, 21L, null, "Ergani", null, false },
                    { 270L, 21L, null, "Hani", null, false },
                    { 271L, 21L, null, "Hazro", null, false },
                    { 272L, 21L, null, "Kocaköy", null, false },
                    { 273L, 21L, null, "Kulp", null, false },
                    { 274L, 21L, null, "Lice", null, false },
                    { 275L, 21L, null, "Silvan", null, false },
                    { 276L, 22L, null, "Merkez", null, false },
                    { 277L, 22L, null, "Enez", null, false },
                    { 278L, 22L, null, "Havsa", null, false },
                    { 279L, 22L, null, "Ipsala", null, false },
                    { 280L, 22L, null, "Kesan", null, false },
                    { 281L, 22L, null, "Lalapasa", null, false },
                    { 282L, 22L, null, "Meriç", null, false },
                    { 283L, 22L, null, "Süloglu", null, false },
                    { 284L, 22L, null, "Uzunköprü", null, false },
                    { 285L, 23L, null, "Merkez", null, false },
                    { 286L, 23L, null, "Agin", null, false },
                    { 287L, 23L, null, "Alacakaya", null, false },
                    { 288L, 23L, null, "Aricak", null, false },
                    { 289L, 23L, null, "Baskil", null, false },
                    { 290L, 23L, null, "Karakoçan", null, false },
                    { 291L, 23L, null, "Keban", null, false },
                    { 292L, 23L, null, "Kovancilar", null, false },
                    { 293L, 23L, null, "Maden", null, false },
                    { 294L, 23L, null, "Palu", null, false },
                    { 295L, 23L, null, "Sivrice", null, false },
                    { 296L, 24L, null, "Merkez", null, false },
                    { 297L, 24L, null, "Çayirli", null, false },
                    { 298L, 24L, null, "Iliç", null, false },
                    { 299L, 24L, null, "Kemah", null, false },
                    { 300L, 24L, null, "Kemaliye", null, false },
                    { 301L, 24L, null, "Otlukbeli", null, false },
                    { 302L, 24L, null, "Refahiye", null, false },
                    { 303L, 24L, null, "Tercan", null, false },
                    { 304L, 24L, null, "Üzümlü", null, false },
                    { 305L, 25L, null, "Merkez", null, false },
                    { 306L, 25L, null, "Askale", null, false },
                    { 307L, 25L, null, "Çat", null, false },
                    { 308L, 25L, null, "Hinis", null, false },
                    { 309L, 25L, null, "Horasan", null, false },
                    { 310L, 25L, null, "Ilica", null, false },
                    { 311L, 25L, null, "Ispir", null, false },
                    { 312L, 25L, null, "Karaçoban", null, false },
                    { 313L, 25L, null, "Karayazi", null, false },
                    { 314L, 25L, null, "Köprüköy", null, false },
                    { 315L, 25L, null, "Narman", null, false },
                    { 316L, 25L, null, "Oltu", null, false },
                    { 317L, 25L, null, "Olur", null, false },
                    { 318L, 25L, null, "Pasinler", null, false },
                    { 319L, 25L, null, "Pazaryolu", null, false },
                    { 320L, 25L, null, "Senkaya", null, false },
                    { 321L, 25L, null, "Tekman", null, false },
                    { 322L, 25L, null, "Tortum", null, false },
                    { 323L, 25L, null, "Uzundere", null, false },
                    { 324L, 26L, null, "Merkez", null, false },
                    { 325L, 26L, null, "Alpu", null, false },
                    { 326L, 26L, null, "Beylikova", null, false },
                    { 327L, 26L, null, "Çifteler", null, false },
                    { 328L, 26L, null, "Günyüzü", null, false },
                    { 329L, 26L, null, "Han", null, false },
                    { 330L, 26L, null, "Inönü", null, false },
                    { 331L, 26L, null, "Mahmudiye", null, false },
                    { 332L, 26L, null, "Mihalgazi", null, false },
                    { 333L, 26L, null, "Mihaliççik", null, false },
                    { 334L, 26L, null, "Saricakaya", null, false },
                    { 335L, 26L, null, "Seyitgazi", null, false },
                    { 336L, 26L, null, "Sivrihisar", null, false },
                    { 337L, 27L, null, "Merkez", null, false },
                    { 338L, 27L, null, "Araban", null, false },
                    { 339L, 27L, null, "Islahiye", null, false },
                    { 340L, 27L, null, "Kilis", null, false },
                    { 341L, 27L, null, "Kargamis", null, false },
                    { 342L, 27L, null, "Nizip", null, false },
                    { 343L, 27L, null, "Nurdagi", null, false },
                    { 344L, 27L, null, "Oguzeli", null, false },
                    { 345L, 27L, null, "Sahinbey", null, false },
                    { 346L, 27L, null, "Sehitkamil", null, false },
                    { 347L, 27L, null, "Yavuzeli", null, false },
                    { 348L, 28L, null, "Merkez", null, false },
                    { 349L, 28L, null, "Alucra", null, false },
                    { 350L, 28L, null, "Bulancak", null, false },
                    { 351L, 28L, null, "Çamoluk", null, false },
                    { 352L, 28L, null, "Çanakçi", null, false },
                    { 353L, 28L, null, "Dereli", null, false },
                    { 354L, 28L, null, "Dogankent", null, false },
                    { 355L, 28L, null, "Espiye", null, false },
                    { 356L, 28L, null, "Eynesil", null, false },
                    { 357L, 28L, null, "Görele", null, false },
                    { 358L, 28L, null, "Güce", null, false },
                    { 359L, 28L, null, "Kesap", null, false },
                    { 360L, 28L, null, "Piraziz", null, false },
                    { 361L, 28L, null, "Sebinkarahisar", null, false },
                    { 362L, 28L, null, "Tirebolu", null, false },
                    { 363L, 28L, null, "Yaglidere", null, false },
                    { 364L, 29L, null, "Merkez", null, false },
                    { 365L, 29L, null, "Kelkit", null, false },
                    { 366L, 29L, null, "Köse", null, false },
                    { 367L, 29L, null, "Kürtün", null, false },
                    { 368L, 29L, null, "Siran", null, false },
                    { 369L, 29L, null, "Torul", null, false },
                    { 370L, 30L, null, "Merkez", null, false },
                    { 371L, 30L, null, "Çukurca", null, false },
                    { 372L, 30L, null, "Semdinli", null, false },
                    { 373L, 30L, null, "Yüksekova", null, false },
                    { 374L, 31L, null, "Merkez", null, false },
                    { 375L, 31L, null, "Altinözü", null, false },
                    { 376L, 31L, null, "Belen", null, false },
                    { 377L, 31L, null, "Dörtyol", null, false },
                    { 378L, 31L, null, "Erzin", null, false },
                    { 379L, 31L, null, "Hassa", null, false },
                    { 380L, 31L, null, "Iskenderun", null, false },
                    { 381L, 31L, null, "Kirikhan", null, false },
                    { 382L, 31L, null, "Kumlu", null, false },
                    { 383L, 31L, null, "Reyhanli", null, false },
                    { 384L, 31L, null, "Samandagi", null, false },
                    { 385L, 31L, null, "Yayladagi", null, false },
                    { 386L, 32L, null, "Merkez", null, false },
                    { 387L, 32L, null, "Aksu", null, false },
                    { 388L, 32L, null, "Atabey", null, false },
                    { 389L, 32L, null, "Egirdir", null, false },
                    { 390L, 32L, null, "Gelendost", null, false },
                    { 391L, 32L, null, "Gönen", null, false },
                    { 392L, 32L, null, "Keçiborlu", null, false },
                    { 393L, 32L, null, "Senirkent", null, false },
                    { 394L, 32L, null, "Sütçüler", null, false },
                    { 395L, 32L, null, "Sarkikaraag", null, false },
                    { 396L, 32L, null, "Uluborlu", null, false },
                    { 397L, 32L, null, "Yenisarbade", null, false },
                    { 398L, 32L, null, "Yalvaç", null, false },
                    { 399L, 33L, null, "Merkez", null, false },
                    { 400L, 33L, null, "Anamur", null, false },
                    { 401L, 33L, null, "Aydincik", null, false },
                    { 402L, 33L, null, "Bozyazi", null, false },
                    { 403L, 33L, null, "Çamliyayla", null, false },
                    { 404L, 33L, null, "Erdemli", null, false },
                    { 405L, 33L, null, "Gülnar", null, false },
                    { 406L, 33L, null, "Mut", null, false },
                    { 407L, 33L, null, "Silifke", null, false },
                    { 408L, 33L, null, "Tarsus", null, false },
                    { 409L, 34L, null, "Merkez", null, false },
                    { 410L, 34L, null, "Adalar", null, false },
                    { 411L, 34L, null, "Avcilar", null, false },
                    { 412L, 34L, null, "Bagcilar", null, false },
                    { 413L, 34L, null, "Bakirköy", null, false },
                    { 414L, 34L, null, "Bahçelievle", null, false },
                    { 415L, 34L, null, "Bayrampasa", null, false },
                    { 416L, 34L, null, "Besiktas", null, false },
                    { 417L, 34L, null, "Beykoz", null, false },
                    { 418L, 34L, null, "Beyoglu", null, false },
                    { 419L, 34L, null, "Büyükçekmece", null, false },
                    { 420L, 34L, null, "Çatalca", null, false },
                    { 421L, 34L, null, "Eminönü", null, false },
                    { 422L, 34L, null, "Eyüp", null, false },
                    { 423L, 34L, null, "Esenler", null, false },
                    { 424L, 34L, null, "Fatih", null, false },
                    { 425L, 34L, null, "Gaziosmanpasa", null, false },
                    { 426L, 34L, null, "Güngören", null, false },
                    { 427L, 34L, null, "Kadiköy", null, false },
                    { 428L, 34L, null, "Kagithane", null, false },
                    { 429L, 34L, null, "Kartal", null, false },
                    { 430L, 34L, null, "Küçükçekmece", null, false },
                    { 431L, 34L, null, "Maltepe", null, false },
                    { 432L, 34L, null, "Pendik", null, false },
                    { 433L, 34L, null, "Sariyer", null, false },
                    { 434L, 34L, null, "Silivri", null, false },
                    { 435L, 34L, null, "Sultanbeyli", null, false },
                    { 436L, 34L, null, "Sile", null, false },
                    { 437L, 34L, null, "Sisli", null, false },
                    { 438L, 34L, null, "Tuzla", null, false },
                    { 439L, 34L, null, "Ümraniye", null, false },
                    { 440L, 34L, null, "Üsküdar", null, false },
                    { 441L, 34L, null, "Yalova", null, false },
                    { 442L, 34L, null, "Zeytinburnu", null, false },
                    { 443L, 35L, null, "Merkez", null, false },
                    { 444L, 35L, null, "Aliaga", null, false },
                    { 445L, 35L, null, "Bayindir", null, false },
                    { 446L, 35L, null, "Balçova", null, false },
                    { 447L, 35L, null, "Bergama", null, false },
                    { 448L, 35L, null, "Beydag", null, false },
                    { 449L, 35L, null, "Bornova", null, false },
                    { 450L, 35L, null, "Buca", null, false },
                    { 451L, 35L, null, "Çesme", null, false },
                    { 452L, 35L, null, "Çigli", null, false },
                    { 453L, 35L, null, "Dikili", null, false },
                    { 454L, 35L, null, "Foça", null, false },
                    { 455L, 35L, null, "Gaziemir", null, false },
                    { 456L, 35L, null, "Güzelbahçe", null, false },
                    { 457L, 35L, null, "Karaburun", null, false },
                    { 458L, 35L, null, "Karsiyaka", null, false },
                    { 459L, 35L, null, "Kemalpasa", null, false },
                    { 460L, 35L, null, "Kinik", null, false },
                    { 461L, 35L, null, "Kiraz", null, false },
                    { 462L, 35L, null, "Konak", null, false },
                    { 463L, 35L, null, "Menderes", null, false },
                    { 464L, 35L, null, "Menemen", null, false },
                    { 465L, 35L, null, "Narlidere", null, false },
                    { 466L, 35L, null, "Ödemis", null, false },
                    { 467L, 35L, null, "Seferihisar", null, false },
                    { 468L, 35L, null, "Selçuk", null, false },
                    { 469L, 35L, null, "Tire", null, false },
                    { 470L, 35L, null, "Torbali", null, false },
                    { 471L, 35L, null, "Urla", null, false },
                    { 472L, 36L, null, "Merkez", null, false },
                    { 473L, 36L, null, "Akyaka", null, false },
                    { 474L, 36L, null, "Arpaçay", null, false },
                    { 475L, 36L, null, "Digor", null, false },
                    { 476L, 36L, null, "Kagizman", null, false },
                    { 477L, 36L, null, "Sarikamis", null, false },
                    { 478L, 36L, null, "Selim", null, false },
                    { 479L, 36L, null, "Susuz", null, false },
                    { 480L, 37L, null, "Merkez", null, false },
                    { 481L, 37L, null, "Abana", null, false },
                    { 482L, 37L, null, "Agli", null, false },
                    { 483L, 37L, null, "Araç", null, false },
                    { 484L, 37L, null, "Azdavay", null, false },
                    { 485L, 37L, null, "Bozkurt", null, false },
                    { 486L, 37L, null, "Cide", null, false },
                    { 487L, 37L, null, "Çatalzeytin", null, false },
                    { 488L, 37L, null, "Daday", null, false },
                    { 489L, 37L, null, "Devrekani", null, false },
                    { 490L, 37L, null, "Doganyurt", null, false },
                    { 491L, 37L, null, "Hanönü", null, false },
                    { 492L, 37L, null, "Ihsangazi", null, false },
                    { 493L, 37L, null, "Inebolu", null, false },
                    { 494L, 37L, null, "Küre", null, false },
                    { 495L, 37L, null, "Pinarbasi", null, false },
                    { 496L, 37L, null, "Seydiler", null, false },
                    { 497L, 37L, null, "Senpazar", null, false },
                    { 498L, 37L, null, "Tasköprü", null, false },
                    { 499L, 37L, null, "Tosya", null, false },
                    { 500L, 38L, null, "Merkez", null, false },
                    { 501L, 38L, null, "Akkisla", null, false },
                    { 502L, 38L, null, "Bünyan", null, false },
                    { 503L, 38L, null, "Develi", null, false },
                    { 504L, 38L, null, "Felahiye", null, false },
                    { 505L, 38L, null, "Hacilar", null, false },
                    { 506L, 38L, null, "Incesu", null, false },
                    { 507L, 38L, null, "Kocasinan", null, false },
                    { 508L, 38L, null, "Melikgazi", null, false },
                    { 509L, 38L, null, "Özvatan", null, false },
                    { 510L, 38L, null, "Pinarbasi", null, false },
                    { 511L, 38L, null, "Sarioglan", null, false },
                    { 512L, 38L, null, "Sariz", null, false },
                    { 513L, 38L, null, "Talas", null, false },
                    { 514L, 38L, null, "Tomarza", null, false },
                    { 515L, 38L, null, "Yahyali", null, false },
                    { 516L, 38L, null, "Yesilhisar", null, false },
                    { 517L, 39L, null, "Merkez", null, false },
                    { 518L, 39L, null, "Babaeski", null, false },
                    { 519L, 39L, null, "Demirköy", null, false },
                    { 520L, 39L, null, "Kofçaz", null, false },
                    { 521L, 39L, null, "Lüleburgaz", null, false },
                    { 522L, 39L, null, "Pehlivanköy", null, false },
                    { 523L, 39L, null, "Pinarhisar", null, false },
                    { 524L, 39L, null, "Vize", null, false },
                    { 525L, 40L, null, "Merkez", null, false },
                    { 526L, 40L, null, "Akçakent", null, false },
                    { 527L, 40L, null, "Akpinar", null, false },
                    { 528L, 40L, null, "Boztepe", null, false },
                    { 529L, 40L, null, "Çiçekdagi", null, false },
                    { 530L, 40L, null, "Kaman", null, false },
                    { 531L, 40L, null, "Mucur", null, false },
                    { 532L, 41L, null, "Merkez", null, false },
                    { 533L, 41L, null, "Darica", null, false },
                    { 534L, 41L, null, "Gebze", null, false },
                    { 535L, 41L, null, "Gölcük", null, false },
                    { 536L, 41L, null, "Kandira", null, false },
                    { 537L, 41L, null, "Karamürsel", null, false },
                    { 538L, 41L, null, "Körfez", null, false },
                    { 539L, 42L, null, "Merkez", null, false },
                    { 540L, 42L, null, "Ahirli", null, false },
                    { 541L, 42L, null, "Akören", null, false },
                    { 542L, 42L, null, "Aksehir", null, false },
                    { 543L, 42L, null, "Altinekin", null, false },
                    { 544L, 42L, null, "Beysehir", null, false },
                    { 545L, 42L, null, "Bozkir", null, false },
                    { 546L, 42L, null, "Derebucak", null, false },
                    { 547L, 42L, null, "Cihanbeyli", null, false },
                    { 548L, 42L, null, "Çumra", null, false },
                    { 549L, 42L, null, "Çeltik", null, false },
                    { 550L, 42L, null, "Derbent", null, false },
                    { 551L, 42L, null, "Doganhisar", null, false },
                    { 552L, 42L, null, "Emirgazi", null, false },
                    { 553L, 42L, null, "Eregli", null, false },
                    { 554L, 42L, null, "Güneysinir", null, false },
                    { 555L, 42L, null, "Halkapinar", null, false },
                    { 556L, 42L, null, "Hadim", null, false },
                    { 557L, 42L, null, "Hüyük", null, false },
                    { 558L, 42L, null, "Ilgin", null, false },
                    { 559L, 42L, null, "Kadinhani", null, false },
                    { 560L, 42L, null, "Karapinar", null, false },
                    { 561L, 42L, null, "Karatay", null, false },
                    { 562L, 42L, null, "Kulu", null, false },
                    { 563L, 42L, null, "Meram", null, false },
                    { 564L, 42L, null, "Sarayönü", null, false },
                    { 565L, 42L, null, "Selçuklu", null, false },
                    { 566L, 42L, null, "Seydisehir", null, false },
                    { 567L, 42L, null, "Taskent", null, false },
                    { 568L, 42L, null, "Tuzlukçu", null, false },
                    { 569L, 42L, null, "Yalihöyük", null, false },
                    { 570L, 42L, null, "Yunak", null, false },
                    { 571L, 43L, null, "Merkez", null, false },
                    { 572L, 43L, null, "Altintas", null, false },
                    { 573L, 43L, null, "Aslanapa", null, false },
                    { 574L, 43L, null, "Cavdarhisar", null, false },
                    { 575L, 43L, null, "Domaniç", null, false },
                    { 576L, 43L, null, "Dumlupinar", null, false },
                    { 577L, 43L, null, "Emet", null, false },
                    { 578L, 43L, null, "Gediz", null, false },
                    { 579L, 43L, null, "Hisarcik", null, false },
                    { 580L, 43L, null, "Pazarlar", null, false },
                    { 581L, 43L, null, "Simav", null, false },
                    { 582L, 43L, null, "Saphane", null, false },
                    { 583L, 43L, null, "Tavsanli", null, false },
                    { 584L, 44L, null, "Merkez", null, false },
                    { 585L, 44L, null, "Akçadag", null, false },
                    { 586L, 44L, null, "Arapgir", null, false },
                    { 587L, 44L, null, "Arguvan", null, false },
                    { 588L, 44L, null, "Battalgazi", null, false },
                    { 589L, 44L, null, "Darende", null, false },
                    { 590L, 44L, null, "Dogansehir", null, false },
                    { 591L, 44L, null, "Doganyol", null, false },
                    { 592L, 44L, null, "Hekimhan", null, false },
                    { 593L, 44L, null, "Kale", null, false },
                    { 594L, 44L, null, "Kuluncak", null, false },
                    { 595L, 44L, null, "Pötürge", null, false },
                    { 596L, 44L, null, "Yazihan", null, false },
                    { 597L, 44L, null, "Yesilyurt", null, false },
                    { 598L, 45L, null, "Merkez", null, false },
                    { 599L, 45L, null, "Ahmetli", null, false },
                    { 600L, 45L, null, "Akhisar", null, false },
                    { 601L, 45L, null, "Alasehir", null, false },
                    { 602L, 45L, null, "Demirci", null, false },
                    { 603L, 45L, null, "Gölmarmara", null, false },
                    { 604L, 45L, null, "Gördes", null, false },
                    { 605L, 45L, null, "Kirkagaç", null, false },
                    { 606L, 45L, null, "Köprübasi", null, false },
                    { 607L, 45L, null, "Kula", null, false },
                    { 608L, 45L, null, "Salihli", null, false },
                    { 609L, 45L, null, "Sarigöl", null, false },
                    { 610L, 45L, null, "Saruhanli", null, false },
                    { 611L, 45L, null, "Selendi", null, false },
                    { 612L, 45L, null, "Soma", null, false },
                    { 613L, 45L, null, "Turgutlu", null, false },
                    { 614L, 46L, null, "Merkez", null, false },
                    { 615L, 46L, null, "Afsin", null, false },
                    { 616L, 46L, null, "Andirin", null, false },
                    { 617L, 46L, null, "Çaglayancer", null, false },
                    { 618L, 46L, null, "Ekinözü", null, false },
                    { 619L, 46L, null, "Elbistan", null, false },
                    { 620L, 46L, null, "Göksun", null, false },
                    { 621L, 46L, null, "Nurhak", null, false },
                    { 622L, 46L, null, "Pazarcik", null, false },
                    { 623L, 46L, null, "Türkoglu", null, false },
                    { 624L, 47L, null, "Merkez", null, false },
                    { 625L, 47L, null, "Dargeçit", null, false },
                    { 626L, 47L, null, "Derik", null, false },
                    { 627L, 47L, null, "Kiziltepe", null, false },
                    { 628L, 47L, null, "Mazidagi", null, false },
                    { 629L, 47L, null, "Midyat", null, false },
                    { 630L, 47L, null, "Nusaybin", null, false },
                    { 631L, 47L, null, "Ömerli", null, false },
                    { 632L, 47L, null, "Savur", null, false },
                    { 633L, 47L, null, "Yesilli", null, false },
                    { 634L, 48L, null, "Merkez", null, false },
                    { 635L, 48L, null, "Bodrum", null, false },
                    { 636L, 48L, null, "Dalaman", null, false },
                    { 637L, 48L, null, "Datça", null, false },
                    { 638L, 48L, null, "Fethiye", null, false },
                    { 639L, 48L, null, "Kavaklidere", null, false },
                    { 640L, 48L, null, "Köycegiz", null, false },
                    { 641L, 48L, null, "Marmaris", null, false },
                    { 642L, 48L, null, "Milas", null, false },
                    { 643L, 48L, null, "Ortaca", null, false },
                    { 644L, 48L, null, "Ula", null, false },
                    { 645L, 48L, null, "Yatagan", null, false },
                    { 646L, 49L, null, "Merkez", null, false },
                    { 647L, 49L, null, "Bulanik", null, false },
                    { 648L, 49L, null, "Hasköy", null, false },
                    { 649L, 49L, null, "Korkut", null, false },
                    { 650L, 49L, null, "Malazgirt", null, false },
                    { 651L, 49L, null, "Varto", null, false },
                    { 652L, 50L, null, "Merkez", null, false },
                    { 653L, 50L, null, "Acigöl", null, false },
                    { 654L, 50L, null, "Avanos", null, false },
                    { 655L, 50L, null, "Derinkuyu", null, false },
                    { 656L, 50L, null, "Gülsehir", null, false },
                    { 657L, 50L, null, "Hacibektas", null, false },
                    { 658L, 50L, null, "Kozakli", null, false },
                    { 659L, 50L, null, "Ürgüp", null, false },
                    { 660L, 51L, null, "Merkez", null, false },
                    { 661L, 51L, null, "Altunhisar", null, false },
                    { 662L, 51L, null, "Bor", null, false },
                    { 663L, 51L, null, "Çamardi", null, false },
                    { 664L, 51L, null, "Çiftlik", null, false },
                    { 665L, 51L, null, "Ulukisla", null, false },
                    { 666L, 52L, null, "Merkez", null, false },
                    { 667L, 52L, null, "Akkus", null, false },
                    { 668L, 52L, null, "Aybasti", null, false },
                    { 669L, 52L, null, "Çamas", null, false },
                    { 670L, 52L, null, "Çatalpinar", null, false },
                    { 671L, 52L, null, "Çaybasi", null, false },
                    { 672L, 52L, null, "Fatsa", null, false },
                    { 673L, 52L, null, "Gölköy", null, false },
                    { 674L, 52L, null, "Gölyali", null, false },
                    { 675L, 52L, null, "Gürgentepe", null, false },
                    { 676L, 52L, null, "Ikizce", null, false },
                    { 677L, 52L, null, "Korgan", null, false },
                    { 678L, 52L, null, "Kabadüz", null, false },
                    { 679L, 52L, null, "Kabatas", null, false },
                    { 680L, 52L, null, "Kumru", null, false },
                    { 681L, 52L, null, "Mesudiye", null, false },
                    { 682L, 52L, null, "Persembe", null, false },
                    { 683L, 52L, null, "Ulubey", null, false },
                    { 684L, 52L, null, "Ünye", null, false },
                    { 685L, 53L, null, "Merkez", null, false },
                    { 686L, 53L, null, "Ardesen", null, false },
                    { 687L, 53L, null, "Çamlihemsin", null, false },
                    { 688L, 53L, null, "Çayeli", null, false },
                    { 689L, 53L, null, "Derepazari", null, false },
                    { 690L, 53L, null, "Findikli", null, false },
                    { 691L, 53L, null, "Güneysu", null, false },
                    { 692L, 53L, null, "Hemsin", null, false },
                    { 693L, 53L, null, "Ikizdere", null, false },
                    { 694L, 53L, null, "Iyidere", null, false },
                    { 695L, 53L, null, "Kalkandere", null, false },
                    { 696L, 53L, null, "Pazar", null, false },
                    { 697L, 54L, null, "Merkez", null, false },
                    { 698L, 54L, null, "Akyazi", null, false },
                    { 699L, 54L, null, "Ferizli", null, false },
                    { 700L, 54L, null, "Geyve", null, false },
                    { 701L, 54L, null, "Hendek", null, false },
                    { 702L, 54L, null, "Karapürçek", null, false },
                    { 703L, 54L, null, "Karasu", null, false },
                    { 704L, 54L, null, "Kaynarca", null, false },
                    { 705L, 54L, null, "Kocaali", null, false },
                    { 706L, 54L, null, "Pamukova", null, false },
                    { 707L, 54L, null, "Sapanca", null, false },
                    { 708L, 54L, null, "Sögütlü", null, false },
                    { 709L, 54L, null, "Tarakli", null, false },
                    { 710L, 55L, null, "Merkez", null, false },
                    { 711L, 55L, null, "Alaçam", null, false },
                    { 712L, 55L, null, "Asarcik", null, false },
                    { 713L, 55L, null, "Ayvacik", null, false },
                    { 714L, 55L, null, "Bafra", null, false },
                    { 715L, 55L, null, "Çarsamba", null, false },
                    { 716L, 55L, null, "Havza", null, false },
                    { 717L, 55L, null, "Kavak", null, false },
                    { 718L, 55L, null, "Ladik", null, false },
                    { 719L, 55L, null, "19mayis", null, false },
                    { 720L, 55L, null, "Salipazari", null, false },
                    { 721L, 55L, null, "Tekkeköy", null, false },
                    { 722L, 55L, null, "Terme", null, false },
                    { 723L, 55L, null, "Vezirköprü", null, false },
                    { 724L, 55L, null, "Yakakent", null, false },
                    { 725L, 56L, null, "Merkez", null, false },
                    { 726L, 56L, null, "Aydinlar", null, false },
                    { 727L, 56L, null, "Baykan", null, false },
                    { 728L, 56L, null, "Eruh", null, false },
                    { 729L, 56L, null, "Kozluk", null, false },
                    { 730L, 56L, null, "Kurtalan", null, false },
                    { 731L, 56L, null, "Pervari", null, false },
                    { 732L, 56L, null, "Sirvan", null, false },
                    { 733L, 57L, null, "Merkez", null, false },
                    { 734L, 57L, null, "Ayancik", null, false },
                    { 735L, 57L, null, "Boyabat", null, false },
                    { 736L, 57L, null, "Dikmen", null, false },
                    { 737L, 57L, null, "Duragan", null, false },
                    { 738L, 57L, null, "Erfelek", null, false },
                    { 739L, 57L, null, "Gerze", null, false },
                    { 740L, 57L, null, "Saraydüzü", null, false },
                    { 741L, 57L, null, "Türkeli", null, false },
                    { 742L, 58L, null, "Merkez", null, false },
                    { 743L, 58L, null, "Akincilar", null, false },
                    { 744L, 58L, null, "Altinyayla", null, false },
                    { 745L, 58L, null, "Divrigi", null, false },
                    { 746L, 58L, null, "Dogansar", null, false },
                    { 747L, 58L, null, "Gemerek", null, false },
                    { 748L, 58L, null, "Gölova", null, false },
                    { 749L, 58L, null, "Gürün", null, false },
                    { 750L, 58L, null, "Hafik", null, false },
                    { 751L, 58L, null, "Imranli", null, false },
                    { 752L, 58L, null, "Kangal", null, false },
                    { 753L, 58L, null, "Koyulhisar", null, false },
                    { 754L, 58L, null, "Susehri", null, false },
                    { 755L, 58L, null, "Sarkisla", null, false },
                    { 756L, 58L, null, "Ulas", null, false },
                    { 757L, 58L, null, "Yildizeli", null, false },
                    { 758L, 58L, null, "Zara", null, false },
                    { 759L, 59L, null, "Merkez", null, false },
                    { 760L, 59L, null, "Çerkezköy", null, false },
                    { 761L, 59L, null, "Çorlu", null, false },
                    { 762L, 59L, null, "Hayrabolu", null, false },
                    { 763L, 59L, null, "Malkara", null, false },
                    { 764L, 59L, null, "Marmaraeregli", null, false },
                    { 765L, 59L, null, "Muratli", null, false },
                    { 766L, 59L, null, "Saray", null, false },
                    { 767L, 59L, null, "Sarköy", null, false },
                    { 768L, 60L, null, "Merkez", null, false },
                    { 769L, 60L, null, "Almus", null, false },
                    { 770L, 60L, null, "Artova", null, false },
                    { 771L, 60L, null, "Basçiftlik", null, false },
                    { 772L, 60L, null, "Erbaa", null, false },
                    { 773L, 60L, null, "Niksar", null, false },
                    { 774L, 60L, null, "Pazar", null, false },
                    { 775L, 60L, null, "Resadiye", null, false },
                    { 776L, 60L, null, "Sulusaray", null, false },
                    { 777L, 60L, null, "Turhal", null, false },
                    { 778L, 60L, null, "Yesilyurt", null, false },
                    { 779L, 60L, null, "Zile", null, false },
                    { 780L, 61L, null, "Merkez", null, false },
                    { 781L, 61L, null, "Akçaabat", null, false },
                    { 782L, 61L, null, "Arakli", null, false },
                    { 783L, 61L, null, "Arsin", null, false },
                    { 784L, 61L, null, "Besikdüzü", null, false },
                    { 785L, 61L, null, "Çarsibasi", null, false },
                    { 786L, 61L, null, "Çaykara", null, false },
                    { 787L, 61L, null, "Dernekpazar", null, false },
                    { 788L, 61L, null, "Düzköy", null, false },
                    { 789L, 61L, null, "Hayrat", null, false },
                    { 790L, 61L, null, "Köprübasi", null, false },
                    { 791L, 61L, null, "Maçka", null, false },
                    { 792L, 61L, null, "Of", null, false },
                    { 793L, 61L, null, "Sürmene", null, false },
                    { 794L, 61L, null, "Salpazari", null, false },
                    { 795L, 61L, null, "Tonya", null, false },
                    { 796L, 61L, null, "Vakfikebir", null, false },
                    { 797L, 61L, null, "Yomra", null, false },
                    { 798L, 62L, null, "Merkez", null, false },
                    { 799L, 62L, null, "Çemisgezek", null, false },
                    { 800L, 62L, null, "Hozat", null, false },
                    { 801L, 62L, null, "Mazgirt", null, false },
                    { 802L, 62L, null, "Nazimiye", null, false },
                    { 803L, 62L, null, "Ovacik", null, false },
                    { 804L, 62L, null, "Pertek", null, false },
                    { 805L, 62L, null, "Pülümür", null, false },
                    { 806L, 63L, null, "Merkez", null, false },
                    { 807L, 63L, null, "Akçakale", null, false },
                    { 808L, 63L, null, "Birecik", null, false },
                    { 809L, 63L, null, "Bozova", null, false },
                    { 810L, 63L, null, "Ceylanpinar", null, false },
                    { 811L, 63L, null, "Halfeti", null, false },
                    { 812L, 63L, null, "Harran", null, false },
                    { 813L, 63L, null, "Hilvan", null, false },
                    { 814L, 63L, null, "Siverek", null, false },
                    { 815L, 63L, null, "Suruç", null, false },
                    { 816L, 63L, null, "Viransehir", null, false },
                    { 817L, 64L, null, "Merkez", null, false },
                    { 818L, 64L, null, "Banaz", null, false },
                    { 819L, 64L, null, "Esme", null, false },
                    { 820L, 64L, null, "Karahalli", null, false },
                    { 821L, 64L, null, "Sivasli", null, false },
                    { 822L, 64L, null, "Ulubey", null, false },
                    { 823L, 65L, null, "Merkez", null, false },
                    { 824L, 65L, null, "Bahçesaray", null, false },
                    { 825L, 65L, null, "Baskale", null, false },
                    { 826L, 65L, null, "Çaldiran", null, false },
                    { 827L, 65L, null, "Çatak", null, false },
                    { 828L, 65L, null, "Edremit", null, false },
                    { 829L, 65L, null, "Ercis", null, false },
                    { 830L, 65L, null, "Gevas", null, false },
                    { 831L, 65L, null, "Gürpinar", null, false },
                    { 832L, 65L, null, "Muradiye", null, false },
                    { 833L, 65L, null, "Özalp", null, false },
                    { 834L, 65L, null, "Saray", null, false },
                    { 835L, 66L, null, "Merkez", null, false },
                    { 836L, 66L, null, "Akdagmadeni", null, false },
                    { 837L, 66L, null, "Aydincik", null, false },
                    { 838L, 66L, null, "Bogazliyan", null, false },
                    { 839L, 66L, null, "Çandir", null, false },
                    { 840L, 66L, null, "Çayiralan", null, false },
                    { 841L, 66L, null, "Çekerek", null, false },
                    { 842L, 66L, null, "Kadisehri", null, false },
                    { 843L, 66L, null, "Sarikaya", null, false },
                    { 844L, 66L, null, "Saraykent", null, false },
                    { 845L, 66L, null, "Sorgun", null, false },
                    { 846L, 66L, null, "Sefaatli", null, false },
                    { 847L, 66L, null, "Yenifakili", null, false },
                    { 848L, 66L, null, "Yerköy", null, false },
                    { 849L, 67L, null, "Merkez", null, false },
                    { 850L, 67L, null, "Alapli", null, false },
                    { 851L, 67L, null, "Çamoluk", null, false },
                    { 852L, 67L, null, "Çaycuma", null, false },
                    { 853L, 67L, null, "Devrek", null, false },
                    { 854L, 67L, null, "Eflani", null, false },
                    { 855L, 67L, null, "Eregli", null, false },
                    { 856L, 67L, null, "Gökçebey", null, false },
                    { 857L, 68L, null, "Merkez", null, false },
                    { 858L, 68L, null, "Agaçören", null, false },
                    { 859L, 68L, null, "Eskil", null, false },
                    { 860L, 68L, null, "Gülagaç", null, false },
                    { 861L, 68L, null, "Güzelyurt", null, false },
                    { 862L, 68L, null, "Ortaköy", null, false },
                    { 863L, 68L, null, "Sariyahsi", null, false },
                    { 864L, 69L, null, "Merkez", null, false },
                    { 865L, 69L, null, "Aydintepe", null, false },
                    { 866L, 69L, null, "Demirözü", null, false },
                    { 867L, 70L, null, "Merkez", null, false },
                    { 868L, 70L, null, "Ayranci", null, false },
                    { 869L, 70L, null, "Basyayla", null, false },
                    { 870L, 70L, null, "Ermenek", null, false },
                    { 871L, 70L, null, "Kazimkarabekir", null, false },
                    { 872L, 70L, null, "Sariveliler", null, false },
                    { 873L, 71L, null, "Merkez", null, false },
                    { 874L, 71L, null, "Bahsili", null, false },
                    { 875L, 71L, null, "Bagliseyh", null, false },
                    { 876L, 71L, null, "Çelebi", null, false },
                    { 877L, 71L, null, "Delice", null, false },
                    { 878L, 71L, null, "Karakeçili", null, false },
                    { 879L, 71L, null, "Keskin", null, false },
                    { 880L, 71L, null, "Sulakyurt", null, false },
                    { 881L, 71L, null, "Yahsihan", null, false },
                    { 882L, 72L, null, "Merkez", null, false },
                    { 883L, 72L, null, "Gercüs", null, false },
                    { 884L, 72L, null, "Hasankeyf", null, false },
                    { 885L, 72L, null, "Besiri", null, false },
                    { 886L, 72L, null, "Kozluk", null, false },
                    { 887L, 72L, null, "Sason", null, false },
                    { 888L, 73L, null, "Merkez", null, false },
                    { 889L, 73L, null, "Beytüsseba", null, false },
                    { 890L, 73L, null, "Uludere", null, false },
                    { 891L, 73L, null, "Cizre", null, false },
                    { 892L, 73L, null, "Idil", null, false },
                    { 893L, 73L, null, "Silopi", null, false },
                    { 894L, 73L, null, "Güçlükonak", null, false },
                    { 895L, 74L, null, "Merkez", null, false },
                    { 896L, 74L, null, "Amasra", null, false },
                    { 897L, 74L, null, "Kurucasile", null, false },
                    { 898L, 74L, null, "Ulus", null, false },
                    { 899L, 75L, null, "Merkez", null, false },
                    { 900L, 75L, null, "Çildir", null, false },
                    { 901L, 75L, null, "Damal", null, false },
                    { 902L, 75L, null, "Göle", null, false },
                    { 903L, 75L, null, "Hanak", null, false },
                    { 904L, 75L, null, "Posof", null, false },
                    { 905L, 76L, null, "Merkez", null, false },
                    { 906L, 76L, null, "Aralik", null, false },
                    { 907L, 76L, null, "Karakoyunlu", null, false },
                    { 908L, 76L, null, "Tuzluca", null, false },
                    { 909L, 77L, null, "Merkez", null, false },
                    { 910L, 77L, null, "Altinova", null, false },
                    { 911L, 77L, null, "Armutlu", null, false },
                    { 912L, 77L, null, "Cinarcik", null, false },
                    { 913L, 77L, null, "Ciftlikkoy", null, false },
                    { 914L, 77L, null, "Termal", null, false },
                    { 915L, 78L, null, "Merkez", null, false },
                    { 916L, 78L, null, "Eflani", null, false },
                    { 917L, 78L, null, "Eskipazar", null, false },
                    { 918L, 78L, null, "Ovacik", null, false },
                    { 919L, 78L, null, "Safranbolu", null, false },
                    { 920L, 78L, null, "Yenice", null, false },
                    { 921L, 79L, null, "Merkez", null, false },
                    { 922L, 79L, null, "Elbeyli", null, false },
                    { 923L, 79L, null, "Musabeyli", null, false },
                    { 924L, 79L, null, "Polateli", null, false },
                    { 925L, 80L, null, "Merkez", null, false },
                    { 926L, 80L, null, "Bahçe", null, false },
                    { 927L, 80L, null, "Hasanbeyli", null, false },
                    { 928L, 80L, null, "Düziçi", null, false },
                    { 929L, 80L, null, "Kadirli", null, false },
                    { 930L, 80L, null, "Sunbas", null, false },
                    { 931L, 80L, null, "Toprakkale", null, false },
                    { 932L, 81L, null, "Merkez", null, false },
                    { 933L, 81L, null, "Akçakoca", null, false },
                    { 934L, 81L, null, "Cumayeri", null, false },
                    { 935L, 81L, null, "Çilimli", null, false },
                    { 936L, 81L, null, "Gölyaka", null, false },
                    { 937L, 81L, null, "Gümüsova", null, false },
                    { 938L, 81L, null, "Kaynasli", null, false },
                    { 939L, 81L, null, "Yigilca", null, false }
                });

            migrationBuilder.InsertData(
                table: "Estates",
                columns: new[] { "Id", "BuildingAge", "CreatedDate", "DistrictId", "Dsc", "EstateType", "FieldM2", "HeaderDsc", "Price", "RentType", "UpdatedDate", "isDeleted" },
                values: new object[,]
                {
                    { 1L, 3, null, 1L, null, 0, 123L, "Estate 1", 1000m, 0, null, false },
                    { 2L, 1, null, 2L, null, 1, 200L, "Estate 2", 800m, 1, null, false },
                    { 3L, 12, null, 3L, null, 2, 80L, "Estate 3", 5000m, 0, null, false },
                    { 4L, 6, null, 70L, null, 1, 170L, "Estate 4", 2500m, 0, null, false },
                    { 5L, 4, null, 71L, null, 0, 90L, "Estate 5", 2400m, 1, null, false },
                    { 6L, 7, null, 72L, null, 3, 90L, "Estate 6", 2600m, 1, null, false },
                    { 7L, 5, null, 73L, null, 3, 250L, "Estate 7", 3000m, 0, null, false },
                    { 8L, 8, null, 180L, null, 0, 230L, "Estate 8", 2300m, 1, null, false }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Districts_CountryId",
                table: "Districts",
                column: "CountryId");

            migrationBuilder.CreateIndex(
                name: "IX_Estates_DistrictId",
                table: "Estates",
                column: "DistrictId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Estates");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "Districts");

            migrationBuilder.DropTable(
                name: "Countries");
        }
    }
}
