using Core.Entities;
using Core.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;
using static Npgsql.PostgresTypes.PostgresCompositeType;

namespace Repository.Context
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

        DbSet<User> Users { get; set; }

        DbSet<Estate> Estates { get; set; }
        DbSet<Country> Countries { get; set; }
        DbSet<District> Districts { get; set; }



        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Global turn off delete behaviour on foreign keys
            foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.SetNull;
                //"cascade" pricipal obje silinirse child objeler silinir.
                //"setnull" pricipal obje silinirse child objeler foreign_key i null yapılır.

            }
            modelBuilder.Entity<Estate>().HasData(
                new Estate() { Id = 1, HeaderDsc = "Estate 1", BuildingAge = 3, EstateType = EstateTypeEnum.Flat, RentType = RentTypeEnum.ForSale, Price = 1000, FieldM2 = 123, isDeleted = false, DistrictId = 1 },
                new Estate() { Id = 2, HeaderDsc = "Estate 2", BuildingAge = 1, EstateType = EstateTypeEnum.Residence, RentType = RentTypeEnum.Rental, Price = 800, FieldM2 = 200, isDeleted = false, DistrictId = 2 },
                new Estate() { Id = 3, HeaderDsc = "Estate 3", BuildingAge = 12, EstateType = EstateTypeEnum.Villa, RentType = RentTypeEnum.ForSale, Price = 5000, FieldM2 = 80, isDeleted = false, DistrictId = 3 },
                new Estate() { Id = 4, HeaderDsc = "Estate 4", BuildingAge = 6, EstateType = EstateTypeEnum.Residence, RentType = RentTypeEnum.ForSale, Price = 2500, FieldM2 = 170, isDeleted = false, DistrictId = 70 },
                new Estate() { Id = 5, HeaderDsc = "Estate 5", BuildingAge = 4, EstateType = EstateTypeEnum.Flat, RentType = RentTypeEnum.Rental, Price = 2400, FieldM2 = 90, isDeleted = false, DistrictId = 71 },
                new Estate() { Id = 6, HeaderDsc = "Estate 6", BuildingAge = 7, EstateType = EstateTypeEnum.Mansion, RentType = RentTypeEnum.Rental, Price = 2600, FieldM2 = 90, isDeleted = false, DistrictId = 72 },
                new Estate() { Id = 7, HeaderDsc = "Estate 7", BuildingAge = 5, EstateType = EstateTypeEnum.Mansion, RentType = RentTypeEnum.ForSale, Price = 3000, FieldM2 = 250, isDeleted = false, DistrictId = 73 },
                new Estate() { Id = 8, HeaderDsc = "Estate 8", BuildingAge = 8, EstateType = EstateTypeEnum.Flat, RentType = RentTypeEnum.Rental, Price = 2300, FieldM2 = 230, isDeleted = false, DistrictId = 180 }
            );


            modelBuilder.Entity<Country>().HasData(
                new Country() { Id = 1, CountryName = "Adana" },
                new Country() { Id = 2, CountryName = "Adiyaman" },
                new Country() { Id = 3, CountryName = "Afyon" },
                new Country() { Id = 4, CountryName = "Ağri" },
                new Country() { Id = 5, CountryName = "Amasya" },
                new Country() { Id = 6, CountryName = "Ankara" },
                new Country() { Id = 7, CountryName = "Antalya" },
                new Country() { Id = 8, CountryName = "Artvin" },
                new Country() { Id = 9, CountryName = "Aydin" },
                new Country() { Id = 10, CountryName = "Balikesir" },
                new Country() { Id = 11, CountryName = "Bilecik" },
                new Country() { Id = 12, CountryName = "Bingöl" },
                new Country() { Id = 13, CountryName = "Bitlis" },
                new Country() { Id = 14, CountryName = "Bolu" },
                new Country() { Id = 15, CountryName = "Burdur" },
                new Country() { Id = 16, CountryName = "Bursa" },
                new Country() { Id = 17, CountryName = "Çanakkale" },
                new Country() { Id = 18, CountryName = "Çankiri" },
                new Country() { Id = 19, CountryName = "Çorum" },
                new Country() { Id = 20, CountryName = "Denizlİ" },
                new Country() { Id = 21, CountryName = "Diyarbakir" },
                new Country() { Id = 22, CountryName = "Edirne" },
                new Country() { Id = 23, CountryName = "Elaziğ" },
                new Country() { Id = 24, CountryName = "Erzincan" },
                new Country() { Id = 25, CountryName = "Erzurum" },
                new Country() { Id = 26, CountryName = "Eskişehir" },
                new Country() { Id = 27, CountryName = "Gaziantep" },
                new Country() { Id = 28, CountryName = "Giresun" },
                new Country() { Id = 29, CountryName = "Gümüşhane" },
                new Country() { Id = 30, CountryName = "Hakkari" },
                new Country() { Id = 31, CountryName = "Hatay" },
                new Country() { Id = 32, CountryName = "Isparta" },
                new Country() { Id = 33, CountryName = "İçel" },
                new Country() { Id = 34, CountryName = "İstanbul" },
                new Country() { Id = 35, CountryName = "İzmir" },
                new Country() { Id = 36, CountryName = "Kars" },
                new Country() { Id = 37, CountryName = "Kastamonu" },
                new Country() { Id = 38, CountryName = "Kayserİ" },
                new Country() { Id = 39, CountryName = "Kirklareli" },
                new Country() { Id = 40, CountryName = "Kirşehir" },
                new Country() { Id = 41, CountryName = "Kocaeli" },
                new Country() { Id = 42, CountryName = "Konya" },
                new Country() { Id = 43, CountryName = "Kütahya" },
                new Country() { Id = 44, CountryName = "Malatya" },
                new Country() { Id = 45, CountryName = "Manisa" },
                new Country() { Id = 46, CountryName = "Kahramanmaraş" },
                new Country() { Id = 47, CountryName = "Mardin" },
                new Country() { Id = 48, CountryName = "Muğla" },
                new Country() { Id = 49, CountryName = "Muş" },
                new Country() { Id = 50, CountryName = "Nevşehir" },
                new Country() { Id = 51, CountryName = "Niğde" },
                new Country() { Id = 52, CountryName = "Ordu" },
                new Country() { Id = 53, CountryName = "Rize" },
                new Country() { Id = 54, CountryName = "Sakarya" },
                new Country() { Id = 55, CountryName = "Samsun" },
                new Country() { Id = 56, CountryName = "Siirt" },
                new Country() { Id = 57, CountryName = "Sinop" },
                new Country() { Id = 58, CountryName = "Sivas" },
                new Country() { Id = 59, CountryName = "Tekirdağ" },
                new Country() { Id = 60, CountryName = "Tokat" },
                new Country() { Id = 61, CountryName = "Trabzon" },
                new Country() { Id = 62, CountryName = "Tuncelİ" },
                new Country() { Id = 63, CountryName = "Şanliurfa" },
                new Country() { Id = 64, CountryName = "Uşak" },
                new Country() { Id = 65, CountryName = "Van" },
                new Country() { Id = 66, CountryName = "Yozgat" },
                new Country() { Id = 67, CountryName = "Zonguldak" },
                new Country() { Id = 68, CountryName = "Aksaray" },
                new Country() { Id = 69, CountryName = "Bayburt" },
                new Country() { Id = 70, CountryName = "Karaman" },
                new Country() { Id = 71, CountryName = "Kirikkale" },
                new Country() { Id = 72, CountryName = "Batman" },
                new Country() { Id = 73, CountryName = "Şirnak" },
                new Country() { Id = 74, CountryName = "Bartin" },
                new Country() { Id = 75, CountryName = "Ardahan" },
                new Country() { Id = 76, CountryName = "Iğdir" },
                new Country() { Id = 77, CountryName = "Yalova" },
                new Country() { Id = 78, CountryName = "Karabük" },
                new Country() { Id = 79, CountryName = "Kilis" },
                new Country() { Id = 80, CountryName = "Osmaniye" },
                new Country() { Id = 81, CountryName = "Düzce" }

            );
            modelBuilder.Entity<District>().HasData(
                new District() { Id = 1, CountryId = 1, DistrictName = "Merkez" },
                 new District() { Id = 2, CountryId = 1, DistrictName = "Aladag" },
                 new District() { Id = 3, CountryId = 1, DistrictName = "Ceyhan" },
                 new District() { Id = 4, CountryId = 1, DistrictName = "Feke" },
                 new District() { Id = 5, CountryId = 1, DistrictName = "Imamoglu" },
                 new District() { Id = 6, CountryId = 1, DistrictName = "Karaisali" },
                 new District() { Id = 7, CountryId = 1, DistrictName = "Karatas" },
                 new District() { Id = 8, CountryId = 1, DistrictName = "Kozan" },
                 new District() { Id = 9, CountryId = 1, DistrictName = "Pozanti" },
                 new District() { Id = 10, CountryId = 1, DistrictName = "Saimbeyli" },
                 new District() { Id = 11, CountryId = 1, DistrictName = "Seyhan" },
                 new District() { Id = 12, CountryId = 1, DistrictName = "Tufanbeyli" },
                 new District() { Id = 13, CountryId = 1, DistrictName = "Yumurtalik" },
                 new District() { Id = 14, CountryId = 1, DistrictName = "Yüregir" },
                 new District() { Id = 15, CountryId = 2, DistrictName = "Merkez" },
                 new District() { Id = 16, CountryId = 2, DistrictName = "Besni" },
                 new District() { Id = 17, CountryId = 2, DistrictName = "Çelikhan" },
                 new District() { Id = 18, CountryId = 2, DistrictName = "Gerger" },
                 new District() { Id = 19, CountryId = 2, DistrictName = "Gölbasi" },
                 new District() { Id = 20, CountryId = 2, DistrictName = "Kahta" },
                 new District() { Id = 21, CountryId = 2, DistrictName = "Samsat" },
                 new District() { Id = 22, CountryId = 2, DistrictName = "Sincik" },
                 new District() { Id = 23, CountryId = 2, DistrictName = "Tut" },
                 new District() { Id = 24, CountryId = 3, DistrictName = "Merkez" },
                 new District() { Id = 25, CountryId = 3, DistrictName = "Basmakçi" },
                 new District() { Id = 26, CountryId = 3, DistrictName = "Bayat" },
                 new District() { Id = 27, CountryId = 3, DistrictName = "Bolvadin" },
                 new District() { Id = 28, CountryId = 3, DistrictName = "Çobanlar" },
                 new District() { Id = 29, CountryId = 3, DistrictName = "Çay" },
                 new District() { Id = 30, CountryId = 3, DistrictName = "Dazkiri" },
                 new District() { Id = 31, CountryId = 3, DistrictName = "Dinar" },
                 new District() { Id = 32, CountryId = 3, DistrictName = "Emirdag" },
                 new District() { Id = 33, CountryId = 3, DistrictName = "Evciler" },
                 new District() { Id = 34, CountryId = 3, DistrictName = "Hocalar" },
                 new District() { Id = 35, CountryId = 3, DistrictName = "Ihsaniye" },
                 new District() { Id = 36, CountryId = 3, DistrictName = "Iscehisar" },
                 new District() { Id = 37, CountryId = 3, DistrictName = "Kizilören" },
                 new District() { Id = 38, CountryId = 3, DistrictName = "Sandikli" },
                 new District() { Id = 39, CountryId = 3, DistrictName = "Sincanli" },
                 new District() { Id = 40, CountryId = 3, DistrictName = "Sultandagi" },
                 new District() { Id = 41, CountryId = 3, DistrictName = "Suhut" },
                 new District() { Id = 42, CountryId = 4, DistrictName = "Merkez" },
                 new District() { Id = 43, CountryId = 4, DistrictName = "Diyadin" },
                 new District() { Id = 44, CountryId = 4, DistrictName = "Dogubeyazit" },
                 new District() { Id = 45, CountryId = 4, DistrictName = "Eleskirt" },
                 new District() { Id = 46, CountryId = 4, DistrictName = "Hamur" },
                 new District() { Id = 47, CountryId = 4, DistrictName = "Patnos" },
                 new District() { Id = 48, CountryId = 4, DistrictName = "Tasliçay" },
                 new District() { Id = 49, CountryId = 4, DistrictName = "Tutak" },
                 new District() { Id = 50, CountryId = 5, DistrictName = "Merkez" },
                 new District() { Id = 51, CountryId = 5, DistrictName = "Göynücek" },
                 new District() { Id = 52, CountryId = 5, DistrictName = "Gümüshacikö" },
                 new District() { Id = 53, CountryId = 5, DistrictName = "Hamamözü" },
                 new District() { Id = 54, CountryId = 5, DistrictName = "Merzifon" },
                 new District() { Id = 55, CountryId = 5, DistrictName = "Suluova" },
                 new District() { Id = 56, CountryId = 5, DistrictName = "Tasova" },
                 new District() { Id = 57, CountryId = 6, DistrictName = "Merkez" },
                 new District() { Id = 58, CountryId = 6, DistrictName = "Akyurt" },
                 new District() { Id = 59, CountryId = 6, DistrictName = "Altindag" },
                 new District() { Id = 60, CountryId = 6, DistrictName = "Ayas" },
                 new District() { Id = 61, CountryId = 6, DistrictName = "Bala" },
                 new District() { Id = 62, CountryId = 6, DistrictName = "Beypazari" },
                 new District() { Id = 63, CountryId = 6, DistrictName = "Çamlidere" },
                 new District() { Id = 64, CountryId = 6, DistrictName = "Çankaya" },
                 new District() { Id = 65, CountryId = 6, DistrictName = "Çubuk" },
                 new District() { Id = 66, CountryId = 6, DistrictName = "Elmadag" },
                 new District() { Id = 67, CountryId = 6, DistrictName = "Etimesgut" },
                 new District() { Id = 68, CountryId = 6, DistrictName = "Evren" },
                 new District() { Id = 69, CountryId = 6, DistrictName = "Gölbasi" },
                 new District() { Id = 70, CountryId = 6, DistrictName = "Güdül" },
                 new District() { Id = 71, CountryId = 6, DistrictName = "Haymana" },
                 new District() { Id = 72, CountryId = 6, DistrictName = "Kalecik" },
                 new District() { Id = 73, CountryId = 6, DistrictName = "Kazan" },
                 new District() { Id = 74, CountryId = 6, DistrictName = "Keçiören" },
                 new District() { Id = 75, CountryId = 6, DistrictName = "Kizilcahama" },
                 new District() { Id = 76, CountryId = 6, DistrictName = "Mamak" },
                 new District() { Id = 77, CountryId = 6, DistrictName = "Nallihan" },
                 new District() { Id = 78, CountryId = 6, DistrictName = "Polatli" },
                 new District() { Id = 79, CountryId = 6, DistrictName = "Sincan" },
                 new District() { Id = 80, CountryId = 6, DistrictName = "Sereflikoçh" },
                 new District() { Id = 81, CountryId = 6, DistrictName = "Yenimahalle" },
                 new District() { Id = 82, CountryId = 7, DistrictName = "Merkez" },
                 new District() { Id = 83, CountryId = 7, DistrictName = "Akseki" },
                 new District() { Id = 84, CountryId = 7, DistrictName = "Alanya" },
                 new District() { Id = 85, CountryId = 7, DistrictName = "Demre" },
                 new District() { Id = 86, CountryId = 7, DistrictName = "Elmali" },
                 new District() { Id = 87, CountryId = 7, DistrictName = "Finike" },
                 new District() { Id = 88, CountryId = 7, DistrictName = "Gazipasa" },
                 new District() { Id = 89, CountryId = 7, DistrictName = "Gündogmus" },
                 new District() { Id = 90, CountryId = 7, DistrictName = "Ibradi" },
                 new District() { Id = 91, CountryId = 7, DistrictName = "Kale" },
                 new District() { Id = 92, CountryId = 7, DistrictName = "Kas" },
                 new District() { Id = 93, CountryId = 7, DistrictName = "Kemer" },
                 new District() { Id = 94, CountryId = 7, DistrictName = "Korkuteli" },
                 new District() { Id = 95, CountryId = 7, DistrictName = "Kumluca" },
                 new District() { Id = 96, CountryId = 7, DistrictName = "Manavgat" },
                 new District() { Id = 97, CountryId = 7, DistrictName = "Serik" },
                 new District() { Id = 98, CountryId = 8, DistrictName = "Merkez" },
                 new District() { Id = 99, CountryId = 8, DistrictName = "Ardanuç" },
                 new District() { Id = 100, CountryId = 8, DistrictName = "Arhavi" },
                 new District() { Id = 101, CountryId = 8, DistrictName = "Borçka" },
                 new District() { Id = 102, CountryId = 8, DistrictName = "Hopa" },
                 new District() { Id = 103, CountryId = 8, DistrictName = "Murgul" },
                 new District() { Id = 104, CountryId = 8, DistrictName = "Savsat" },
                 new District() { Id = 105, CountryId = 8, DistrictName = "Yusufeli" },
                 new District() { Id = 106, CountryId = 9, DistrictName = "Merkez" },
                 new District() { Id = 107, CountryId = 9, DistrictName = "Bozdogan" },
                 new District() { Id = 108, CountryId = 9, DistrictName = "Buharkent" },
                 new District() { Id = 109, CountryId = 9, DistrictName = "Çine" },
                 new District() { Id = 110, CountryId = 9, DistrictName = "Germencik" },
                 new District() { Id = 111, CountryId = 9, DistrictName = "Incirliova" },
                 new District() { Id = 112, CountryId = 9, DistrictName = "Karacasu" },
                 new District() { Id = 113, CountryId = 9, DistrictName = "Karpuzlu" },
                 new District() { Id = 114, CountryId = 9, DistrictName = "Koçarli" },
                 new District() { Id = 115, CountryId = 9, DistrictName = "Kösk" },
                 new District() { Id = 116, CountryId = 9, DistrictName = "Kusadasi" },
                 new District() { Id = 117, CountryId = 9, DistrictName = "Kuyucak" },
                 new District() { Id = 118, CountryId = 9, DistrictName = "Nazilli" },
                 new District() { Id = 119, CountryId = 9, DistrictName = "Söke" },
                 new District() { Id = 120, CountryId = 9, DistrictName = "Sultanhisar" },
                 new District() { Id = 121, CountryId = 9, DistrictName = "Yenihisar" },
                 new District() { Id = 122, CountryId = 9, DistrictName = "Yenipazar" },
                 new District() { Id = 123, CountryId = 10, DistrictName = "Merkez" },
                 new District() { Id = 124, CountryId = 10, DistrictName = "Ayvalik" },
                 new District() { Id = 125, CountryId = 10, DistrictName = "Akçay" },
                 new District() { Id = 126, CountryId = 10, DistrictName = "Balya" },
                 new District() { Id = 127, CountryId = 10, DistrictName = "Bandirma" },
                 new District() { Id = 128, CountryId = 10, DistrictName = "Bigadiç" },
                 new District() { Id = 129, CountryId = 10, DistrictName = "Burhaniye" },
                 new District() { Id = 130, CountryId = 10, DistrictName = "Dursunbey" },
                 new District() { Id = 131, CountryId = 10, DistrictName = "Edremit" },
                 new District() { Id = 132, CountryId = 10, DistrictName = "Erdek" },
                 new District() { Id = 133, CountryId = 10, DistrictName = "Gönen" },
                 new District() { Id = 134, CountryId = 10, DistrictName = "Gömeç" },
                 new District() { Id = 135, CountryId = 10, DistrictName = "Havran" },
                 new District() { Id = 136, CountryId = 10, DistrictName = "Ivrindi" },
                 new District() { Id = 137, CountryId = 10, DistrictName = "Kepsut" },
                 new District() { Id = 138, CountryId = 10, DistrictName = "Manyas" },
                 new District() { Id = 139, CountryId = 10, DistrictName = "Marmara" },
                 new District() { Id = 140, CountryId = 10, DistrictName = "Savastepe" },
                 new District() { Id = 141, CountryId = 10, DistrictName = "Sindirgi" },
                 new District() { Id = 142, CountryId = 10, DistrictName = "Susurluk" },
                 new District() { Id = 143, CountryId = 11, DistrictName = "Merkez" },
                 new District() { Id = 144, CountryId = 11, DistrictName = "Bozöyük" },
                 new District() { Id = 145, CountryId = 11, DistrictName = "Gölpazari" },
                 new District() { Id = 146, CountryId = 11, DistrictName = "Inhisar" },
                 new District() { Id = 147, CountryId = 11, DistrictName = "Osmaneli" },
                 new District() { Id = 148, CountryId = 11, DistrictName = "Pazaryeri" },
                 new District() { Id = 149, CountryId = 11, DistrictName = "Sögüt" },
                 new District() { Id = 150, CountryId = 11, DistrictName = "Yenipazar" },
                 new District() { Id = 151, CountryId = 12, DistrictName = "Merkez" },
                 new District() { Id = 152, CountryId = 12, DistrictName = "Adakli" },
                 new District() { Id = 153, CountryId = 12, DistrictName = "Genç" },
                 new District() { Id = 154, CountryId = 12, DistrictName = "Karliova" },
                 new District() { Id = 155, CountryId = 12, DistrictName = "Kigi" },
                 new District() { Id = 156, CountryId = 12, DistrictName = "Solhan" },
                 new District() { Id = 157, CountryId = 12, DistrictName = "Yayladere" },
                 new District() { Id = 158, CountryId = 12, DistrictName = "Yedisu" },
                 new District() { Id = 159, CountryId = 13, DistrictName = "Merkez" },
                 new District() { Id = 160, CountryId = 13, DistrictName = "Adilcevaz" },
                 new District() { Id = 161, CountryId = 13, DistrictName = "Ahlat" },
                 new District() { Id = 162, CountryId = 13, DistrictName = "Güroymak" },
                 new District() { Id = 163, CountryId = 13, DistrictName = "Hizan" },
                 new District() { Id = 164, CountryId = 13, DistrictName = "Mutki" },
                 new District() { Id = 165, CountryId = 13, DistrictName = "Tatvan" },
                 new District() { Id = 166, CountryId = 14, DistrictName = "Merkez" },
                 new District() { Id = 167, CountryId = 14, DistrictName = "Dörtdivan" },
                 new District() { Id = 168, CountryId = 14, DistrictName = "Gerede" },
                 new District() { Id = 169, CountryId = 14, DistrictName = "Göynük" },
                 new District() { Id = 170, CountryId = 14, DistrictName = "Kibriscik" },
                 new District() { Id = 171, CountryId = 14, DistrictName = "Mengen" },
                 new District() { Id = 172, CountryId = 14, DistrictName = "Mudurnu" },
                 new District() { Id = 173, CountryId = 14, DistrictName = "Seben" },
                 new District() { Id = 174, CountryId = 14, DistrictName = "Yeniçaga" },
                 new District() { Id = 175, CountryId = 15, DistrictName = "Merkez" },
                 new District() { Id = 176, CountryId = 15, DistrictName = "Altinyayla" },
                 new District() { Id = 177, CountryId = 15, DistrictName = "Aglasun" },
                 new District() { Id = 178, CountryId = 15, DistrictName = "Bucak" },
                 new District() { Id = 179, CountryId = 15, DistrictName = "Çavdir" },
                 new District() { Id = 180, CountryId = 15, DistrictName = "Çeltikçi" },
                 new District() { Id = 181, CountryId = 15, DistrictName = "Gölhisar" },
                 new District() { Id = 182, CountryId = 15, DistrictName = "Karamanli" },
                 new District() { Id = 183, CountryId = 15, DistrictName = "Kemer" },
                 new District() { Id = 184, CountryId = 15, DistrictName = "Tefenni" },
                 new District() { Id = 185, CountryId = 15, DistrictName = "Yesilova" },
                 new District() { Id = 186, CountryId = 16, DistrictName = "Merkez" },
                 new District() { Id = 187, CountryId = 16, DistrictName = "Büyükorhan" },
                 new District() { Id = 188, CountryId = 16, DistrictName = "Gemlik" },
                 new District() { Id = 189, CountryId = 16, DistrictName = "Gürsu" },
                 new District() { Id = 190, CountryId = 16, DistrictName = "Harmancik" },
                 new District() { Id = 191, CountryId = 16, DistrictName = "Inegöl" },
                 new District() { Id = 192, CountryId = 16, DistrictName = "Iznik" },
                 new District() { Id = 193, CountryId = 16, DistrictName = "Karacabey" },
                 new District() { Id = 194, CountryId = 16, DistrictName = "Keles" },
                 new District() { Id = 195, CountryId = 16, DistrictName = "Kestel" },
                 new District() { Id = 196, CountryId = 16, DistrictName = "Mudanya" },
                 new District() { Id = 197, CountryId = 16, DistrictName = "Mustafakema" },
                 new District() { Id = 198, CountryId = 16, DistrictName = "Nilüfer" },
                 new District() { Id = 199, CountryId = 16, DistrictName = "Orhaneli" },
                 new District() { Id = 200, CountryId = 16, DistrictName = "Orhangazi" },
                 new District() { Id = 201, CountryId = 16, DistrictName = "Osmangazi" },
                 new District() { Id = 202, CountryId = 16, DistrictName = "Yenisehir" },
                 new District() { Id = 203, CountryId = 16, DistrictName = "Yildirim" },
                 new District() { Id = 204, CountryId = 17, DistrictName = "Merkez" },
                 new District() { Id = 205, CountryId = 17, DistrictName = "Ayvacik" },
                 new District() { Id = 206, CountryId = 17, DistrictName = "Bayramiç" },
                 new District() { Id = 207, CountryId = 17, DistrictName = "Bozcaada" },
                 new District() { Id = 208, CountryId = 17, DistrictName = "Biga" },
                 new District() { Id = 209, CountryId = 17, DistrictName = "Çan" },
                 new District() { Id = 210, CountryId = 17, DistrictName = "Eceabat" },
                 new District() { Id = 211, CountryId = 17, DistrictName = "Ezine" },
                 new District() { Id = 212, CountryId = 17, DistrictName = "Gelibolu" },
                 new District() { Id = 213, CountryId = 17, DistrictName = "Gökçeada" },
                 new District() { Id = 214, CountryId = 17, DistrictName = "Lapseki" },
                 new District() { Id = 215, CountryId = 17, DistrictName = "Yenice" },
                 new District() { Id = 216, CountryId = 18, DistrictName = "Merkez" },
                 new District() { Id = 217, CountryId = 18, DistrictName = "Atkaracalar" },
                 new District() { Id = 218, CountryId = 18, DistrictName = "Bayramören" },
                 new District() { Id = 219, CountryId = 18, DistrictName = "Çerkes" },
                 new District() { Id = 220, CountryId = 18, DistrictName = "Eldivan" },
                 new District() { Id = 221, CountryId = 18, DistrictName = "Ilgaz" },
                 new District() { Id = 222, CountryId = 18, DistrictName = "Kizilirmak" },
                 new District() { Id = 223, CountryId = 18, DistrictName = "Korgun" },
                 new District() { Id = 224, CountryId = 18, DistrictName = "Kursunlu" },
                 new District() { Id = 225, CountryId = 18, DistrictName = "Orta" },
                 new District() { Id = 226, CountryId = 18, DistrictName = "Ovacik" },
                 new District() { Id = 227, CountryId = 18, DistrictName = "Sabanözü" },
                 new District() { Id = 228, CountryId = 18, DistrictName = "Yaprakli" },
                 new District() { Id = 229, CountryId = 19, DistrictName = "Merkez" },
                 new District() { Id = 230, CountryId = 19, DistrictName = "Alaca" },
                 new District() { Id = 231, CountryId = 19, DistrictName = "Bayat" },
                 new District() { Id = 232, CountryId = 19, DistrictName = "Bogazkale" },
                 new District() { Id = 233, CountryId = 19, DistrictName = "Dodurga" },
                 new District() { Id = 234, CountryId = 19, DistrictName = "Iskilip" },
                 new District() { Id = 235, CountryId = 19, DistrictName = "Kargi" },
                 new District() { Id = 236, CountryId = 19, DistrictName = "Laçin" },
                 new District() { Id = 237, CountryId = 19, DistrictName = "Mecitözü" },
                 new District() { Id = 238, CountryId = 19, DistrictName = "Oguzlar" },
                 new District() { Id = 239, CountryId = 19, DistrictName = "Ortaköy" },
                 new District() { Id = 240, CountryId = 19, DistrictName = "Osmancik" },
                 new District() { Id = 241, CountryId = 19, DistrictName = "Sungurlu" },
                 new District() { Id = 242, CountryId = 19, DistrictName = "Ugurludag" },
                 new District() { Id = 243, CountryId = 20, DistrictName = "Merkez" },
                 new District() { Id = 244, CountryId = 20, DistrictName = "Acipayam" },
                 new District() { Id = 245, CountryId = 20, DistrictName = "Akköy" },
                 new District() { Id = 246, CountryId = 20, DistrictName = "Babadag" },
                 new District() { Id = 247, CountryId = 20, DistrictName = "Baklan" },
                 new District() { Id = 248, CountryId = 20, DistrictName = "Bekilli" },
                 new District() { Id = 249, CountryId = 20, DistrictName = "Beyagaç" },
                 new District() { Id = 250, CountryId = 20, DistrictName = "Buldan" },
                 new District() { Id = 251, CountryId = 20, DistrictName = "Bozkurt" },
                 new District() { Id = 252, CountryId = 20, DistrictName = "Çal" },
                 new District() { Id = 253, CountryId = 20, DistrictName = "Çameli" },
                 new District() { Id = 254, CountryId = 20, DistrictName = "Çardak" },
                 new District() { Id = 255, CountryId = 20, DistrictName = "Çivril" },
                 new District() { Id = 256, CountryId = 20, DistrictName = "Güney" },
                 new District() { Id = 257, CountryId = 20, DistrictName = "Honaz" },
                 new District() { Id = 258, CountryId = 20, DistrictName = "Kale" },
                 new District() { Id = 259, CountryId = 20, DistrictName = "Sarayköy" },
                 new District() { Id = 260, CountryId = 20, DistrictName = "Serinhisar" },
                 new District() { Id = 261, CountryId = 20, DistrictName = "Tavas" },
                 new District() { Id = 262, CountryId = 21, DistrictName = "Merkez" },
                 new District() { Id = 263, CountryId = 21, DistrictName = "Bismil" },
                 new District() { Id = 264, CountryId = 21, DistrictName = "Çermik" },
                 new District() { Id = 265, CountryId = 21, DistrictName = "Çinar" },
                 new District() { Id = 266, CountryId = 21, DistrictName = "Çüngüs" },
                 new District() { Id = 267, CountryId = 21, DistrictName = "Dicle" },
                 new District() { Id = 268, CountryId = 21, DistrictName = "Egil" },
                 new District() { Id = 269, CountryId = 21, DistrictName = "Ergani" },
                 new District() { Id = 270, CountryId = 21, DistrictName = "Hani" },
                 new District() { Id = 271, CountryId = 21, DistrictName = "Hazro" },
                 new District() { Id = 272, CountryId = 21, DistrictName = "Kocaköy" },
                 new District() { Id = 273, CountryId = 21, DistrictName = "Kulp" },
                 new District() { Id = 274, CountryId = 21, DistrictName = "Lice" },
                 new District() { Id = 275, CountryId = 21, DistrictName = "Silvan" },
                 new District() { Id = 276, CountryId = 22, DistrictName = "Merkez" },
                 new District() { Id = 277, CountryId = 22, DistrictName = "Enez" },
                 new District() { Id = 278, CountryId = 22, DistrictName = "Havsa" },
                 new District() { Id = 279, CountryId = 22, DistrictName = "Ipsala" },
                 new District() { Id = 280, CountryId = 22, DistrictName = "Kesan" },
                 new District() { Id = 281, CountryId = 22, DistrictName = "Lalapasa" },
                 new District() { Id = 282, CountryId = 22, DistrictName = "Meriç" },
                 new District() { Id = 283, CountryId = 22, DistrictName = "Süloglu" },
                 new District() { Id = 284, CountryId = 22, DistrictName = "Uzunköprü" },
                 new District() { Id = 285, CountryId = 23, DistrictName = "Merkez" },
                 new District() { Id = 286, CountryId = 23, DistrictName = "Agin" },
                 new District() { Id = 287, CountryId = 23, DistrictName = "Alacakaya" },
                 new District() { Id = 288, CountryId = 23, DistrictName = "Aricak" },
                 new District() { Id = 289, CountryId = 23, DistrictName = "Baskil" },
                 new District() { Id = 290, CountryId = 23, DistrictName = "Karakoçan" },
                 new District() { Id = 291, CountryId = 23, DistrictName = "Keban" },
                 new District() { Id = 292, CountryId = 23, DistrictName = "Kovancilar" },
                 new District() { Id = 293, CountryId = 23, DistrictName = "Maden" },
                 new District() { Id = 294, CountryId = 23, DistrictName = "Palu" },
                 new District() { Id = 295, CountryId = 23, DistrictName = "Sivrice" },
                 new District() { Id = 296, CountryId = 24, DistrictName = "Merkez" },
                 new District() { Id = 297, CountryId = 24, DistrictName = "Çayirli" },
                 new District() { Id = 298, CountryId = 24, DistrictName = "Iliç" },
                 new District() { Id = 299, CountryId = 24, DistrictName = "Kemah" },
                 new District() { Id = 300, CountryId = 24, DistrictName = "Kemaliye" },
                 new District() { Id = 301, CountryId = 24, DistrictName = "Otlukbeli" },
                 new District() { Id = 302, CountryId = 24, DistrictName = "Refahiye" },
                 new District() { Id = 303, CountryId = 24, DistrictName = "Tercan" },
                 new District() { Id = 304, CountryId = 24, DistrictName = "Üzümlü" },
                 new District() { Id = 305, CountryId = 25, DistrictName = "Merkez" },
                 new District() { Id = 306, CountryId = 25, DistrictName = "Askale" },
                 new District() { Id = 307, CountryId = 25, DistrictName = "Çat" },
                 new District() { Id = 308, CountryId = 25, DistrictName = "Hinis" },
                 new District() { Id = 309, CountryId = 25, DistrictName = "Horasan" },
                 new District() { Id = 310, CountryId = 25, DistrictName = "Ilica" },
                 new District() { Id = 311, CountryId = 25, DistrictName = "Ispir" },
                 new District() { Id = 312, CountryId = 25, DistrictName = "Karaçoban" },
                 new District() { Id = 313, CountryId = 25, DistrictName = "Karayazi" },
                 new District() { Id = 314, CountryId = 25, DistrictName = "Köprüköy" },
                 new District() { Id = 315, CountryId = 25, DistrictName = "Narman" },
                 new District() { Id = 316, CountryId = 25, DistrictName = "Oltu" },
                 new District() { Id = 317, CountryId = 25, DistrictName = "Olur" },
                 new District() { Id = 318, CountryId = 25, DistrictName = "Pasinler" },
                 new District() { Id = 319, CountryId = 25, DistrictName = "Pazaryolu" },
                 new District() { Id = 320, CountryId = 25, DistrictName = "Senkaya" },
                 new District() { Id = 321, CountryId = 25, DistrictName = "Tekman" },
                 new District() { Id = 322, CountryId = 25, DistrictName = "Tortum" },
                 new District() { Id = 323, CountryId = 25, DistrictName = "Uzundere" },
                 new District() { Id = 324, CountryId = 26, DistrictName = "Merkez" },
                 new District() { Id = 325, CountryId = 26, DistrictName = "Alpu" },
                 new District() { Id = 326, CountryId = 26, DistrictName = "Beylikova" },
                 new District() { Id = 327, CountryId = 26, DistrictName = "Çifteler" },
                 new District() { Id = 328, CountryId = 26, DistrictName = "Günyüzü" },
                 new District() { Id = 329, CountryId = 26, DistrictName = "Han" },
                 new District() { Id = 330, CountryId = 26, DistrictName = "Inönü" },
                 new District() { Id = 331, CountryId = 26, DistrictName = "Mahmudiye" },
                 new District() { Id = 332, CountryId = 26, DistrictName = "Mihalgazi" },
                 new District() { Id = 333, CountryId = 26, DistrictName = "Mihaliççik" },
                 new District() { Id = 334, CountryId = 26, DistrictName = "Saricakaya" },
                 new District() { Id = 335, CountryId = 26, DistrictName = "Seyitgazi" },
                 new District() { Id = 336, CountryId = 26, DistrictName = "Sivrihisar" },
                 new District() { Id = 337, CountryId = 27, DistrictName = "Merkez" },
                 new District() { Id = 338, CountryId = 27, DistrictName = "Araban" },
                 new District() { Id = 339, CountryId = 27, DistrictName = "Islahiye" },
                 new District() { Id = 340, CountryId = 27, DistrictName = "Kilis" },
                 new District() { Id = 341, CountryId = 27, DistrictName = "Kargamis" },
                 new District() { Id = 342, CountryId = 27, DistrictName = "Nizip" },
                 new District() { Id = 343, CountryId = 27, DistrictName = "Nurdagi" },
                 new District() { Id = 344, CountryId = 27, DistrictName = "Oguzeli" },
                 new District() { Id = 345, CountryId = 27, DistrictName = "Sahinbey" },
                 new District() { Id = 346, CountryId = 27, DistrictName = "Sehitkamil" },
                 new District() { Id = 347, CountryId = 27, DistrictName = "Yavuzeli" },
                 new District() { Id = 348, CountryId = 28, DistrictName = "Merkez" },
                 new District() { Id = 349, CountryId = 28, DistrictName = "Alucra" },
                 new District() { Id = 350, CountryId = 28, DistrictName = "Bulancak" },
                 new District() { Id = 351, CountryId = 28, DistrictName = "Çamoluk" },
                 new District() { Id = 352, CountryId = 28, DistrictName = "Çanakçi" },
                 new District() { Id = 353, CountryId = 28, DistrictName = "Dereli" },
                 new District() { Id = 354, CountryId = 28, DistrictName = "Dogankent" },
                 new District() { Id = 355, CountryId = 28, DistrictName = "Espiye" },
                 new District() { Id = 356, CountryId = 28, DistrictName = "Eynesil" },
                 new District() { Id = 357, CountryId = 28, DistrictName = "Görele" },
                 new District() { Id = 358, CountryId = 28, DistrictName = "Güce" },
                 new District() { Id = 359, CountryId = 28, DistrictName = "Kesap" },
                 new District() { Id = 360, CountryId = 28, DistrictName = "Piraziz" },
                 new District() { Id = 361, CountryId = 28, DistrictName = "Sebinkarahisar" },
                 new District() { Id = 362, CountryId = 28, DistrictName = "Tirebolu" },
                 new District() { Id = 363, CountryId = 28, DistrictName = "Yaglidere" },
                 new District() { Id = 364, CountryId = 29, DistrictName = "Merkez" },
                 new District() { Id = 365, CountryId = 29, DistrictName = "Kelkit" },
                 new District() { Id = 366, CountryId = 29, DistrictName = "Köse" },
                 new District() { Id = 367, CountryId = 29, DistrictName = "Kürtün" },
                 new District() { Id = 368, CountryId = 29, DistrictName = "Siran" },
                 new District() { Id = 369, CountryId = 29, DistrictName = "Torul" },
                 new District() { Id = 370, CountryId = 30, DistrictName = "Merkez" },
                 new District() { Id = 371, CountryId = 30, DistrictName = "Çukurca" },
                 new District() { Id = 372, CountryId = 30, DistrictName = "Semdinli" },
                 new District() { Id = 373, CountryId = 30, DistrictName = "Yüksekova" },
                 new District() { Id = 374, CountryId = 31, DistrictName = "Merkez" },
                 new District() { Id = 375, CountryId = 31, DistrictName = "Altinözü" },
                 new District() { Id = 376, CountryId = 31, DistrictName = "Belen" },
                 new District() { Id = 377, CountryId = 31, DistrictName = "Dörtyol" },
                 new District() { Id = 378, CountryId = 31, DistrictName = "Erzin" },
                 new District() { Id = 379, CountryId = 31, DistrictName = "Hassa" },
                 new District() { Id = 380, CountryId = 31, DistrictName = "Iskenderun" },
                 new District() { Id = 381, CountryId = 31, DistrictName = "Kirikhan" },
                 new District() { Id = 382, CountryId = 31, DistrictName = "Kumlu" },
                 new District() { Id = 383, CountryId = 31, DistrictName = "Reyhanli" },
                 new District() { Id = 384, CountryId = 31, DistrictName = "Samandagi" },
                 new District() { Id = 385, CountryId = 31, DistrictName = "Yayladagi" },
                 new District() { Id = 386, CountryId = 32, DistrictName = "Merkez" },
                 new District() { Id = 387, CountryId = 32, DistrictName = "Aksu" },
                 new District() { Id = 388, CountryId = 32, DistrictName = "Atabey" },
                 new District() { Id = 389, CountryId = 32, DistrictName = "Egirdir" },
                 new District() { Id = 390, CountryId = 32, DistrictName = "Gelendost" },
                 new District() { Id = 391, CountryId = 32, DistrictName = "Gönen" },
                 new District() { Id = 392, CountryId = 32, DistrictName = "Keçiborlu" },
                 new District() { Id = 393, CountryId = 32, DistrictName = "Senirkent" },
                 new District() { Id = 394, CountryId = 32, DistrictName = "Sütçüler" },
                 new District() { Id = 395, CountryId = 32, DistrictName = "Sarkikaraag" },
                 new District() { Id = 396, CountryId = 32, DistrictName = "Uluborlu" },
                 new District() { Id = 397, CountryId = 32, DistrictName = "Yenisarbade" },
                 new District() { Id = 398, CountryId = 32, DistrictName = "Yalvaç" },
                 new District() { Id = 399, CountryId = 33, DistrictName = "Merkez" },
                 new District() { Id = 400, CountryId = 33, DistrictName = "Anamur" },
                 new District() { Id = 401, CountryId = 33, DistrictName = "Aydincik" },
                 new District() { Id = 402, CountryId = 33, DistrictName = "Bozyazi" },
                 new District() { Id = 403, CountryId = 33, DistrictName = "Çamliyayla" },
                 new District() { Id = 404, CountryId = 33, DistrictName = "Erdemli" },
                 new District() { Id = 405, CountryId = 33, DistrictName = "Gülnar" },
                 new District() { Id = 406, CountryId = 33, DistrictName = "Mut" },
                 new District() { Id = 407, CountryId = 33, DistrictName = "Silifke" },
                 new District() { Id = 408, CountryId = 33, DistrictName = "Tarsus" },
                 new District() { Id = 409, CountryId = 34, DistrictName = "Merkez" },
                 new District() { Id = 410, CountryId = 34, DistrictName = "Adalar" },
                 new District() { Id = 411, CountryId = 34, DistrictName = "Avcilar" },
                 new District() { Id = 412, CountryId = 34, DistrictName = "Bagcilar" },
                 new District() { Id = 413, CountryId = 34, DistrictName = "Bakirköy" },
                 new District() { Id = 414, CountryId = 34, DistrictName = "Bahçelievle" },
                 new District() { Id = 415, CountryId = 34, DistrictName = "Bayrampasa" },
                 new District() { Id = 416, CountryId = 34, DistrictName = "Besiktas" },
                 new District() { Id = 417, CountryId = 34, DistrictName = "Beykoz" },
                 new District() { Id = 418, CountryId = 34, DistrictName = "Beyoglu" },
                 new District() { Id = 419, CountryId = 34, DistrictName = "Büyükçekmece" },
                 new District() { Id = 420, CountryId = 34, DistrictName = "Çatalca" },
                 new District() { Id = 421, CountryId = 34, DistrictName = "Eminönü" },
                 new District() { Id = 422, CountryId = 34, DistrictName = "Eyüp" },
                 new District() { Id = 423, CountryId = 34, DistrictName = "Esenler" },
                 new District() { Id = 424, CountryId = 34, DistrictName = "Fatih" },
                 new District() { Id = 425, CountryId = 34, DistrictName = "Gaziosmanpasa" },
                 new District() { Id = 426, CountryId = 34, DistrictName = "Güngören" },
                 new District() { Id = 427, CountryId = 34, DistrictName = "Kadiköy" },
                 new District() { Id = 428, CountryId = 34, DistrictName = "Kagithane" },
                 new District() { Id = 429, CountryId = 34, DistrictName = "Kartal" },
                 new District() { Id = 430, CountryId = 34, DistrictName = "Küçükçekmece" },
                 new District() { Id = 431, CountryId = 34, DistrictName = "Maltepe" },
                 new District() { Id = 432, CountryId = 34, DistrictName = "Pendik" },
                 new District() { Id = 433, CountryId = 34, DistrictName = "Sariyer" },
                 new District() { Id = 434, CountryId = 34, DistrictName = "Silivri" },
                 new District() { Id = 435, CountryId = 34, DistrictName = "Sultanbeyli" },
                 new District() { Id = 436, CountryId = 34, DistrictName = "Sile" },
                 new District() { Id = 437, CountryId = 34, DistrictName = "Sisli" },
                 new District() { Id = 438, CountryId = 34, DistrictName = "Tuzla" },
                 new District() { Id = 439, CountryId = 34, DistrictName = "Ümraniye" },
                 new District() { Id = 440, CountryId = 34, DistrictName = "Üsküdar" },
                 new District() { Id = 441, CountryId = 34, DistrictName = "Yalova" },
                 new District() { Id = 442, CountryId = 34, DistrictName = "Zeytinburnu" },
                 new District() { Id = 443, CountryId = 35, DistrictName = "Merkez" },
                 new District() { Id = 444, CountryId = 35, DistrictName = "Aliaga" },
                 new District() { Id = 445, CountryId = 35, DistrictName = "Bayindir" },
                 new District() { Id = 446, CountryId = 35, DistrictName = "Balçova" },
                 new District() { Id = 447, CountryId = 35, DistrictName = "Bergama" },
                 new District() { Id = 448, CountryId = 35, DistrictName = "Beydag" },
                 new District() { Id = 449, CountryId = 35, DistrictName = "Bornova" },
                 new District() { Id = 450, CountryId = 35, DistrictName = "Buca" },
                 new District() { Id = 451, CountryId = 35, DistrictName = "Çesme" },
                 new District() { Id = 452, CountryId = 35, DistrictName = "Çigli" },
                 new District() { Id = 453, CountryId = 35, DistrictName = "Dikili" },
                 new District() { Id = 454, CountryId = 35, DistrictName = "Foça" },
                 new District() { Id = 455, CountryId = 35, DistrictName = "Gaziemir" },
                 new District() { Id = 456, CountryId = 35, DistrictName = "Güzelbahçe" },
                 new District() { Id = 457, CountryId = 35, DistrictName = "Karaburun" },
                 new District() { Id = 458, CountryId = 35, DistrictName = "Karsiyaka" },
                 new District() { Id = 459, CountryId = 35, DistrictName = "Kemalpasa" },
                 new District() { Id = 460, CountryId = 35, DistrictName = "Kinik" },
                 new District() { Id = 461, CountryId = 35, DistrictName = "Kiraz" },
                 new District() { Id = 462, CountryId = 35, DistrictName = "Konak" },
                 new District() { Id = 463, CountryId = 35, DistrictName = "Menderes" },
                 new District() { Id = 464, CountryId = 35, DistrictName = "Menemen" },
                 new District() { Id = 465, CountryId = 35, DistrictName = "Narlidere" },
                 new District() { Id = 466, CountryId = 35, DistrictName = "Ödemis" },
                 new District() { Id = 467, CountryId = 35, DistrictName = "Seferihisar" },
                 new District() { Id = 468, CountryId = 35, DistrictName = "Selçuk" },
                 new District() { Id = 469, CountryId = 35, DistrictName = "Tire" },
                 new District() { Id = 470, CountryId = 35, DistrictName = "Torbali" },
                 new District() { Id = 471, CountryId = 35, DistrictName = "Urla" },
                 new District() { Id = 472, CountryId = 36, DistrictName = "Merkez" },
                 new District() { Id = 473, CountryId = 36, DistrictName = "Akyaka" },
                 new District() { Id = 474, CountryId = 36, DistrictName = "Arpaçay" },
                 new District() { Id = 475, CountryId = 36, DistrictName = "Digor" },
                 new District() { Id = 476, CountryId = 36, DistrictName = "Kagizman" },
                 new District() { Id = 477, CountryId = 36, DistrictName = "Sarikamis" },
                 new District() { Id = 478, CountryId = 36, DistrictName = "Selim" },
                 new District() { Id = 479, CountryId = 36, DistrictName = "Susuz" },
                 new District() { Id = 480, CountryId = 37, DistrictName = "Merkez" },
                 new District() { Id = 481, CountryId = 37, DistrictName = "Abana" },
                 new District() { Id = 482, CountryId = 37, DistrictName = "Agli" },
                 new District() { Id = 483, CountryId = 37, DistrictName = "Araç" },
                 new District() { Id = 484, CountryId = 37, DistrictName = "Azdavay" },
                 new District() { Id = 485, CountryId = 37, DistrictName = "Bozkurt" },
                 new District() { Id = 486, CountryId = 37, DistrictName = "Cide" },
                 new District() { Id = 487, CountryId = 37, DistrictName = "Çatalzeytin" },
                 new District() { Id = 488, CountryId = 37, DistrictName = "Daday" },
                 new District() { Id = 489, CountryId = 37, DistrictName = "Devrekani" },
                 new District() { Id = 490, CountryId = 37, DistrictName = "Doganyurt" },
                 new District() { Id = 491, CountryId = 37, DistrictName = "Hanönü" },
                 new District() { Id = 492, CountryId = 37, DistrictName = "Ihsangazi" },
                 new District() { Id = 493, CountryId = 37, DistrictName = "Inebolu" },
                 new District() { Id = 494, CountryId = 37, DistrictName = "Küre" },
                 new District() { Id = 495, CountryId = 37, DistrictName = "Pinarbasi" },
                 new District() { Id = 496, CountryId = 37, DistrictName = "Seydiler" },
                 new District() { Id = 497, CountryId = 37, DistrictName = "Senpazar" },
                 new District() { Id = 498, CountryId = 37, DistrictName = "Tasköprü" },
                 new District() { Id = 499, CountryId = 37, DistrictName = "Tosya" },
                 new District() { Id = 500, CountryId = 38, DistrictName = "Merkez" },
                 new District() { Id = 501, CountryId = 38, DistrictName = "Akkisla" },
                 new District() { Id = 502, CountryId = 38, DistrictName = "Bünyan" },
                 new District() { Id = 503, CountryId = 38, DistrictName = "Develi" },
                 new District() { Id = 504, CountryId = 38, DistrictName = "Felahiye" },
                 new District() { Id = 505, CountryId = 38, DistrictName = "Hacilar" },
                 new District() { Id = 506, CountryId = 38, DistrictName = "Incesu" },
                 new District() { Id = 507, CountryId = 38, DistrictName = "Kocasinan" },
                 new District() { Id = 508, CountryId = 38, DistrictName = "Melikgazi" },
                 new District() { Id = 509, CountryId = 38, DistrictName = "Özvatan" },
                 new District() { Id = 510, CountryId = 38, DistrictName = "Pinarbasi" },
                 new District() { Id = 511, CountryId = 38, DistrictName = "Sarioglan" },
                 new District() { Id = 512, CountryId = 38, DistrictName = "Sariz" },
                 new District() { Id = 513, CountryId = 38, DistrictName = "Talas" },
                 new District() { Id = 514, CountryId = 38, DistrictName = "Tomarza" },
                 new District() { Id = 515, CountryId = 38, DistrictName = "Yahyali" },
                 new District() { Id = 516, CountryId = 38, DistrictName = "Yesilhisar" },
                 new District() { Id = 517, CountryId = 39, DistrictName = "Merkez" },
                 new District() { Id = 518, CountryId = 39, DistrictName = "Babaeski" },
                 new District() { Id = 519, CountryId = 39, DistrictName = "Demirköy" },
                 new District() { Id = 520, CountryId = 39, DistrictName = "Kofçaz" },
                 new District() { Id = 521, CountryId = 39, DistrictName = "Lüleburgaz" },
                 new District() { Id = 522, CountryId = 39, DistrictName = "Pehlivanköy" },
                 new District() { Id = 523, CountryId = 39, DistrictName = "Pinarhisar" },
                 new District() { Id = 524, CountryId = 39, DistrictName = "Vize" },
                 new District() { Id = 525, CountryId = 40, DistrictName = "Merkez" },
                 new District() { Id = 526, CountryId = 40, DistrictName = "Akçakent" },
                 new District() { Id = 527, CountryId = 40, DistrictName = "Akpinar" },
                 new District() { Id = 528, CountryId = 40, DistrictName = "Boztepe" },
                 new District() { Id = 529, CountryId = 40, DistrictName = "Çiçekdagi" },
                 new District() { Id = 530, CountryId = 40, DistrictName = "Kaman" },
                 new District() { Id = 531, CountryId = 40, DistrictName = "Mucur" },
                 new District() { Id = 532, CountryId = 41, DistrictName = "Merkez" },
                 new District() { Id = 533, CountryId = 41, DistrictName = "Darica" },
                 new District() { Id = 534, CountryId = 41, DistrictName = "Gebze" },
                 new District() { Id = 535, CountryId = 41, DistrictName = "Gölcük" },
                 new District() { Id = 536, CountryId = 41, DistrictName = "Kandira" },
                 new District() { Id = 537, CountryId = 41, DistrictName = "Karamürsel" },
                 new District() { Id = 538, CountryId = 41, DistrictName = "Körfez" },
                 new District() { Id = 539, CountryId = 42, DistrictName = "Merkez" },
                 new District() { Id = 540, CountryId = 42, DistrictName = "Ahirli" },
                 new District() { Id = 541, CountryId = 42, DistrictName = "Akören" },
                 new District() { Id = 542, CountryId = 42, DistrictName = "Aksehir" },
                 new District() { Id = 543, CountryId = 42, DistrictName = "Altinekin" },
                 new District() { Id = 544, CountryId = 42, DistrictName = "Beysehir" },
                 new District() { Id = 545, CountryId = 42, DistrictName = "Bozkir" },
                 new District() { Id = 546, CountryId = 42, DistrictName = "Derebucak" },
                 new District() { Id = 547, CountryId = 42, DistrictName = "Cihanbeyli" },
                 new District() { Id = 548, CountryId = 42, DistrictName = "Çumra" },
                 new District() { Id = 549, CountryId = 42, DistrictName = "Çeltik" },
                 new District() { Id = 550, CountryId = 42, DistrictName = "Derbent" },
                 new District() { Id = 551, CountryId = 42, DistrictName = "Doganhisar" },
                 new District() { Id = 552, CountryId = 42, DistrictName = "Emirgazi" },
                 new District() { Id = 553, CountryId = 42, DistrictName = "Eregli" },
                 new District() { Id = 554, CountryId = 42, DistrictName = "Güneysinir" },
                 new District() { Id = 555, CountryId = 42, DistrictName = "Halkapinar" },
                 new District() { Id = 556, CountryId = 42, DistrictName = "Hadim" },
                 new District() { Id = 557, CountryId = 42, DistrictName = "Hüyük" },
                 new District() { Id = 558, CountryId = 42, DistrictName = "Ilgin" },
                 new District() { Id = 559, CountryId = 42, DistrictName = "Kadinhani" },
                 new District() { Id = 560, CountryId = 42, DistrictName = "Karapinar" },
                 new District() { Id = 561, CountryId = 42, DistrictName = "Karatay" },
                 new District() { Id = 562, CountryId = 42, DistrictName = "Kulu" },
                 new District() { Id = 563, CountryId = 42, DistrictName = "Meram" },
                 new District() { Id = 564, CountryId = 42, DistrictName = "Sarayönü" },
                 new District() { Id = 565, CountryId = 42, DistrictName = "Selçuklu" },
                 new District() { Id = 566, CountryId = 42, DistrictName = "Seydisehir" },
                 new District() { Id = 567, CountryId = 42, DistrictName = "Taskent" },
                 new District() { Id = 568, CountryId = 42, DistrictName = "Tuzlukçu" },
                 new District() { Id = 569, CountryId = 42, DistrictName = "Yalihöyük" },
                 new District() { Id = 570, CountryId = 42, DistrictName = "Yunak" },
                 new District() { Id = 571, CountryId = 43, DistrictName = "Merkez" },
                 new District() { Id = 572, CountryId = 43, DistrictName = "Altintas" },
                 new District() { Id = 573, CountryId = 43, DistrictName = "Aslanapa" },
                 new District() { Id = 574, CountryId = 43, DistrictName = "Cavdarhisar" },
                 new District() { Id = 575, CountryId = 43, DistrictName = "Domaniç" },
                 new District() { Id = 576, CountryId = 43, DistrictName = "Dumlupinar" },
                 new District() { Id = 577, CountryId = 43, DistrictName = "Emet" },
                 new District() { Id = 578, CountryId = 43, DistrictName = "Gediz" },
                 new District() { Id = 579, CountryId = 43, DistrictName = "Hisarcik" },
                 new District() { Id = 580, CountryId = 43, DistrictName = "Pazarlar" },
                 new District() { Id = 581, CountryId = 43, DistrictName = "Simav" },
                 new District() { Id = 582, CountryId = 43, DistrictName = "Saphane" },
                 new District() { Id = 583, CountryId = 43, DistrictName = "Tavsanli" },
                 new District() { Id = 584, CountryId = 44, DistrictName = "Merkez" },
                 new District() { Id = 585, CountryId = 44, DistrictName = "Akçadag" },
                 new District() { Id = 586, CountryId = 44, DistrictName = "Arapgir" },
                 new District() { Id = 587, CountryId = 44, DistrictName = "Arguvan" },
                 new District() { Id = 588, CountryId = 44, DistrictName = "Battalgazi" },
                 new District() { Id = 589, CountryId = 44, DistrictName = "Darende" },
                 new District() { Id = 590, CountryId = 44, DistrictName = "Dogansehir" },
                 new District() { Id = 591, CountryId = 44, DistrictName = "Doganyol" },
                 new District() { Id = 592, CountryId = 44, DistrictName = "Hekimhan" },
                 new District() { Id = 593, CountryId = 44, DistrictName = "Kale" },
                 new District() { Id = 594, CountryId = 44, DistrictName = "Kuluncak" },
                 new District() { Id = 595, CountryId = 44, DistrictName = "Pötürge" },
                 new District() { Id = 596, CountryId = 44, DistrictName = "Yazihan" },
                 new District() { Id = 597, CountryId = 44, DistrictName = "Yesilyurt" },
                 new District() { Id = 598, CountryId = 45, DistrictName = "Merkez" },
                 new District() { Id = 599, CountryId = 45, DistrictName = "Ahmetli" },
                 new District() { Id = 600, CountryId = 45, DistrictName = "Akhisar" },
                 new District() { Id = 601, CountryId = 45, DistrictName = "Alasehir" },
                 new District() { Id = 602, CountryId = 45, DistrictName = "Demirci" },
                 new District() { Id = 603, CountryId = 45, DistrictName = "Gölmarmara" },
                 new District() { Id = 604, CountryId = 45, DistrictName = "Gördes" },
                 new District() { Id = 605, CountryId = 45, DistrictName = "Kirkagaç" },
                 new District() { Id = 606, CountryId = 45, DistrictName = "Köprübasi" },
                 new District() { Id = 607, CountryId = 45, DistrictName = "Kula" },
                 new District() { Id = 608, CountryId = 45, DistrictName = "Salihli" },
                 new District() { Id = 609, CountryId = 45, DistrictName = "Sarigöl" },
                 new District() { Id = 610, CountryId = 45, DistrictName = "Saruhanli" },
                 new District() { Id = 611, CountryId = 45, DistrictName = "Selendi" },
                 new District() { Id = 612, CountryId = 45, DistrictName = "Soma" },
                 new District() { Id = 613, CountryId = 45, DistrictName = "Turgutlu" },
                 new District() { Id = 614, CountryId = 46, DistrictName = "Merkez" },
                 new District() { Id = 615, CountryId = 46, DistrictName = "Afsin" },
                 new District() { Id = 616, CountryId = 46, DistrictName = "Andirin" },
                 new District() { Id = 617, CountryId = 46, DistrictName = "Çaglayancer" },
                 new District() { Id = 618, CountryId = 46, DistrictName = "Ekinözü" },
                 new District() { Id = 619, CountryId = 46, DistrictName = "Elbistan" },
                 new District() { Id = 620, CountryId = 46, DistrictName = "Göksun" },
                 new District() { Id = 621, CountryId = 46, DistrictName = "Nurhak" },
                 new District() { Id = 622, CountryId = 46, DistrictName = "Pazarcik" },
                 new District() { Id = 623, CountryId = 46, DistrictName = "Türkoglu" },
                 new District() { Id = 624, CountryId = 47, DistrictName = "Merkez" },
                 new District() { Id = 625, CountryId = 47, DistrictName = "Dargeçit" },
                 new District() { Id = 626, CountryId = 47, DistrictName = "Derik" },
                 new District() { Id = 627, CountryId = 47, DistrictName = "Kiziltepe" },
                 new District() { Id = 628, CountryId = 47, DistrictName = "Mazidagi" },
                 new District() { Id = 629, CountryId = 47, DistrictName = "Midyat" },
                 new District() { Id = 630, CountryId = 47, DistrictName = "Nusaybin" },
                 new District() { Id = 631, CountryId = 47, DistrictName = "Ömerli" },
                 new District() { Id = 632, CountryId = 47, DistrictName = "Savur" },
                 new District() { Id = 633, CountryId = 47, DistrictName = "Yesilli" },
                 new District() { Id = 634, CountryId = 48, DistrictName = "Merkez" },
                 new District() { Id = 635, CountryId = 48, DistrictName = "Bodrum" },
                 new District() { Id = 636, CountryId = 48, DistrictName = "Dalaman" },
                 new District() { Id = 637, CountryId = 48, DistrictName = "Datça" },
                 new District() { Id = 638, CountryId = 48, DistrictName = "Fethiye" },
                 new District() { Id = 639, CountryId = 48, DistrictName = "Kavaklidere" },
                 new District() { Id = 640, CountryId = 48, DistrictName = "Köycegiz" },
                 new District() { Id = 641, CountryId = 48, DistrictName = "Marmaris" },
                 new District() { Id = 642, CountryId = 48, DistrictName = "Milas" },
                 new District() { Id = 643, CountryId = 48, DistrictName = "Ortaca" },
                 new District() { Id = 644, CountryId = 48, DistrictName = "Ula" },
                 new District() { Id = 645, CountryId = 48, DistrictName = "Yatagan" },
                 new District() { Id = 646, CountryId = 49, DistrictName = "Merkez" },
                 new District() { Id = 647, CountryId = 49, DistrictName = "Bulanik" },
                 new District() { Id = 648, CountryId = 49, DistrictName = "Hasköy" },
                 new District() { Id = 649, CountryId = 49, DistrictName = "Korkut" },
                 new District() { Id = 650, CountryId = 49, DistrictName = "Malazgirt" },
                 new District() { Id = 651, CountryId = 49, DistrictName = "Varto" },
                 new District() { Id = 652, CountryId = 50, DistrictName = "Merkez" },
                 new District() { Id = 653, CountryId = 50, DistrictName = "Acigöl" },
                 new District() { Id = 654, CountryId = 50, DistrictName = "Avanos" },
                 new District() { Id = 655, CountryId = 50, DistrictName = "Derinkuyu" },
                 new District() { Id = 656, CountryId = 50, DistrictName = "Gülsehir" },
                 new District() { Id = 657, CountryId = 50, DistrictName = "Hacibektas" },
                 new District() { Id = 658, CountryId = 50, DistrictName = "Kozakli" },
                 new District() { Id = 659, CountryId = 50, DistrictName = "Ürgüp" },
                 new District() { Id = 660, CountryId = 51, DistrictName = "Merkez" },
                 new District() { Id = 661, CountryId = 51, DistrictName = "Altunhisar" },
                 new District() { Id = 662, CountryId = 51, DistrictName = "Bor" },
                 new District() { Id = 663, CountryId = 51, DistrictName = "Çamardi" },
                 new District() { Id = 664, CountryId = 51, DistrictName = "Çiftlik" },
                 new District() { Id = 665, CountryId = 51, DistrictName = "Ulukisla" },
                 new District() { Id = 666, CountryId = 52, DistrictName = "Merkez" },
                 new District() { Id = 667, CountryId = 52, DistrictName = "Akkus" },
                 new District() { Id = 668, CountryId = 52, DistrictName = "Aybasti" },
                 new District() { Id = 669, CountryId = 52, DistrictName = "Çamas" },
                 new District() { Id = 670, CountryId = 52, DistrictName = "Çatalpinar" },
                 new District() { Id = 671, CountryId = 52, DistrictName = "Çaybasi" },
                 new District() { Id = 672, CountryId = 52, DistrictName = "Fatsa" },
                 new District() { Id = 673, CountryId = 52, DistrictName = "Gölköy" },
                 new District() { Id = 674, CountryId = 52, DistrictName = "Gölyali" },
                 new District() { Id = 675, CountryId = 52, DistrictName = "Gürgentepe" },
                 new District() { Id = 676, CountryId = 52, DistrictName = "Ikizce" },
                 new District() { Id = 677, CountryId = 52, DistrictName = "Korgan" },
                 new District() { Id = 678, CountryId = 52, DistrictName = "Kabadüz" },
                 new District() { Id = 679, CountryId = 52, DistrictName = "Kabatas" },
                 new District() { Id = 680, CountryId = 52, DistrictName = "Kumru" },
                 new District() { Id = 681, CountryId = 52, DistrictName = "Mesudiye" },
                 new District() { Id = 682, CountryId = 52, DistrictName = "Persembe" },
                 new District() { Id = 683, CountryId = 52, DistrictName = "Ulubey" },
                 new District() { Id = 684, CountryId = 52, DistrictName = "Ünye" },
                 new District() { Id = 685, CountryId = 53, DistrictName = "Merkez" },
                 new District() { Id = 686, CountryId = 53, DistrictName = "Ardesen" },
                 new District() { Id = 687, CountryId = 53, DistrictName = "Çamlihemsin" },
                 new District() { Id = 688, CountryId = 53, DistrictName = "Çayeli" },
                 new District() { Id = 689, CountryId = 53, DistrictName = "Derepazari" },
                 new District() { Id = 690, CountryId = 53, DistrictName = "Findikli" },
                 new District() { Id = 691, CountryId = 53, DistrictName = "Güneysu" },
                 new District() { Id = 692, CountryId = 53, DistrictName = "Hemsin" },
                 new District() { Id = 693, CountryId = 53, DistrictName = "Ikizdere" },
                 new District() { Id = 694, CountryId = 53, DistrictName = "Iyidere" },
                 new District() { Id = 695, CountryId = 53, DistrictName = "Kalkandere" },
                 new District() { Id = 696, CountryId = 53, DistrictName = "Pazar" },
                 new District() { Id = 697, CountryId = 54, DistrictName = "Merkez" },
                 new District() { Id = 698, CountryId = 54, DistrictName = "Akyazi" },
                 new District() { Id = 699, CountryId = 54, DistrictName = "Ferizli" },
                 new District() { Id = 700, CountryId = 54, DistrictName = "Geyve" },
                 new District() { Id = 701, CountryId = 54, DistrictName = "Hendek" },
                 new District() { Id = 702, CountryId = 54, DistrictName = "Karapürçek" },
                 new District() { Id = 703, CountryId = 54, DistrictName = "Karasu" },
                 new District() { Id = 704, CountryId = 54, DistrictName = "Kaynarca" },
                 new District() { Id = 705, CountryId = 54, DistrictName = "Kocaali" },
                 new District() { Id = 706, CountryId = 54, DistrictName = "Pamukova" },
                 new District() { Id = 707, CountryId = 54, DistrictName = "Sapanca" },
                 new District() { Id = 708, CountryId = 54, DistrictName = "Sögütlü" },
                 new District() { Id = 709, CountryId = 54, DistrictName = "Tarakli" },
                 new District() { Id = 710, CountryId = 55, DistrictName = "Merkez" },
                 new District() { Id = 711, CountryId = 55, DistrictName = "Alaçam" },
                 new District() { Id = 712, CountryId = 55, DistrictName = "Asarcik" },
                 new District() { Id = 713, CountryId = 55, DistrictName = "Ayvacik" },
                 new District() { Id = 714, CountryId = 55, DistrictName = "Bafra" },
                 new District() { Id = 715, CountryId = 55, DistrictName = "Çarsamba" },
                 new District() { Id = 716, CountryId = 55, DistrictName = "Havza" },
                 new District() { Id = 717, CountryId = 55, DistrictName = "Kavak" },
                 new District() { Id = 718, CountryId = 55, DistrictName = "Ladik" },
                 new District() { Id = 719, CountryId = 55, DistrictName = "19mayis" },
                 new District() { Id = 720, CountryId = 55, DistrictName = "Salipazari" },
                 new District() { Id = 721, CountryId = 55, DistrictName = "Tekkeköy" },
                 new District() { Id = 722, CountryId = 55, DistrictName = "Terme" },
                 new District() { Id = 723, CountryId = 55, DistrictName = "Vezirköprü" },
                 new District() { Id = 724, CountryId = 55, DistrictName = "Yakakent" },
                 new District() { Id = 725, CountryId = 56, DistrictName = "Merkez" },
                 new District() { Id = 726, CountryId = 56, DistrictName = "Aydinlar" },
                 new District() { Id = 727, CountryId = 56, DistrictName = "Baykan" },
                 new District() { Id = 728, CountryId = 56, DistrictName = "Eruh" },
                 new District() { Id = 729, CountryId = 56, DistrictName = "Kozluk" },
                 new District() { Id = 730, CountryId = 56, DistrictName = "Kurtalan" },
                 new District() { Id = 731, CountryId = 56, DistrictName = "Pervari" },
                 new District() { Id = 732, CountryId = 56, DistrictName = "Sirvan" },
                 new District() { Id = 733, CountryId = 57, DistrictName = "Merkez" },
                 new District() { Id = 734, CountryId = 57, DistrictName = "Ayancik" },
                 new District() { Id = 735, CountryId = 57, DistrictName = "Boyabat" },
                 new District() { Id = 736, CountryId = 57, DistrictName = "Dikmen" },
                 new District() { Id = 737, CountryId = 57, DistrictName = "Duragan" },
                 new District() { Id = 738, CountryId = 57, DistrictName = "Erfelek" },
                 new District() { Id = 739, CountryId = 57, DistrictName = "Gerze" },
                 new District() { Id = 740, CountryId = 57, DistrictName = "Saraydüzü" },
                 new District() { Id = 741, CountryId = 57, DistrictName = "Türkeli" },
                 new District() { Id = 742, CountryId = 58, DistrictName = "Merkez" },
                 new District() { Id = 743, CountryId = 58, DistrictName = "Akincilar" },
                 new District() { Id = 744, CountryId = 58, DistrictName = "Altinyayla" },
                 new District() { Id = 745, CountryId = 58, DistrictName = "Divrigi" },
                 new District() { Id = 746, CountryId = 58, DistrictName = "Dogansar" },
                 new District() { Id = 747, CountryId = 58, DistrictName = "Gemerek" },
                 new District() { Id = 748, CountryId = 58, DistrictName = "Gölova" },
                 new District() { Id = 749, CountryId = 58, DistrictName = "Gürün" },
                 new District() { Id = 750, CountryId = 58, DistrictName = "Hafik" },
                 new District() { Id = 751, CountryId = 58, DistrictName = "Imranli" },
                 new District() { Id = 752, CountryId = 58, DistrictName = "Kangal" },
                 new District() { Id = 753, CountryId = 58, DistrictName = "Koyulhisar" },
                 new District() { Id = 754, CountryId = 58, DistrictName = "Susehri" },
                 new District() { Id = 755, CountryId = 58, DistrictName = "Sarkisla" },
                 new District() { Id = 756, CountryId = 58, DistrictName = "Ulas" },
                 new District() { Id = 757, CountryId = 58, DistrictName = "Yildizeli" },
                 new District() { Id = 758, CountryId = 58, DistrictName = "Zara" },
                 new District() { Id = 759, CountryId = 59, DistrictName = "Merkez" },
                 new District() { Id = 760, CountryId = 59, DistrictName = "Çerkezköy" },
                 new District() { Id = 761, CountryId = 59, DistrictName = "Çorlu" },
                 new District() { Id = 762, CountryId = 59, DistrictName = "Hayrabolu" },
                 new District() { Id = 763, CountryId = 59, DistrictName = "Malkara" },
                 new District() { Id = 764, CountryId = 59, DistrictName = "Marmaraeregli" },
                 new District() { Id = 765, CountryId = 59, DistrictName = "Muratli" },
                 new District() { Id = 766, CountryId = 59, DistrictName = "Saray" },
                 new District() { Id = 767, CountryId = 59, DistrictName = "Sarköy" },
                 new District() { Id = 768, CountryId = 60, DistrictName = "Merkez" },
                 new District() { Id = 769, CountryId = 60, DistrictName = "Almus" },
                 new District() { Id = 770, CountryId = 60, DistrictName = "Artova" },
                 new District() { Id = 771, CountryId = 60, DistrictName = "Basçiftlik" },
                 new District() { Id = 772, CountryId = 60, DistrictName = "Erbaa" },
                 new District() { Id = 773, CountryId = 60, DistrictName = "Niksar" },
                 new District() { Id = 774, CountryId = 60, DistrictName = "Pazar" },
                 new District() { Id = 775, CountryId = 60, DistrictName = "Resadiye" },
                 new District() { Id = 776, CountryId = 60, DistrictName = "Sulusaray" },
                 new District() { Id = 777, CountryId = 60, DistrictName = "Turhal" },
                 new District() { Id = 778, CountryId = 60, DistrictName = "Yesilyurt" },
                 new District() { Id = 779, CountryId = 60, DistrictName = "Zile" },
                 new District() { Id = 780, CountryId = 61, DistrictName = "Merkez" },
                 new District() { Id = 781, CountryId = 61, DistrictName = "Akçaabat" },
                 new District() { Id = 782, CountryId = 61, DistrictName = "Arakli" },
                 new District() { Id = 783, CountryId = 61, DistrictName = "Arsin" },
                 new District() { Id = 784, CountryId = 61, DistrictName = "Besikdüzü" },
                 new District() { Id = 785, CountryId = 61, DistrictName = "Çarsibasi" },
                 new District() { Id = 786, CountryId = 61, DistrictName = "Çaykara" },
                 new District() { Id = 787, CountryId = 61, DistrictName = "Dernekpazar" },
                 new District() { Id = 788, CountryId = 61, DistrictName = "Düzköy" },
                 new District() { Id = 789, CountryId = 61, DistrictName = "Hayrat" },
                 new District() { Id = 790, CountryId = 61, DistrictName = "Köprübasi" },
                 new District() { Id = 791, CountryId = 61, DistrictName = "Maçka" },
                 new District() { Id = 792, CountryId = 61, DistrictName = "Of" },
                 new District() { Id = 793, CountryId = 61, DistrictName = "Sürmene" },
                 new District() { Id = 794, CountryId = 61, DistrictName = "Salpazari" },
                 new District() { Id = 795, CountryId = 61, DistrictName = "Tonya" },
                 new District() { Id = 796, CountryId = 61, DistrictName = "Vakfikebir" },
                 new District() { Id = 797, CountryId = 61, DistrictName = "Yomra" },
                 new District() { Id = 798, CountryId = 62, DistrictName = "Merkez" },
                 new District() { Id = 799, CountryId = 62, DistrictName = "Çemisgezek" },
                 new District() { Id = 800, CountryId = 62, DistrictName = "Hozat" },
                 new District() { Id = 801, CountryId = 62, DistrictName = "Mazgirt" },
                 new District() { Id = 802, CountryId = 62, DistrictName = "Nazimiye" },
                 new District() { Id = 803, CountryId = 62, DistrictName = "Ovacik" },
                 new District() { Id = 804, CountryId = 62, DistrictName = "Pertek" },
                 new District() { Id = 805, CountryId = 62, DistrictName = "Pülümür" },
                 new District() { Id = 806, CountryId = 63, DistrictName = "Merkez" },
                 new District() { Id = 807, CountryId = 63, DistrictName = "Akçakale" },
                 new District() { Id = 808, CountryId = 63, DistrictName = "Birecik" },
                 new District() { Id = 809, CountryId = 63, DistrictName = "Bozova" },
                 new District() { Id = 810, CountryId = 63, DistrictName = "Ceylanpinar" },
                 new District() { Id = 811, CountryId = 63, DistrictName = "Halfeti" },
                 new District() { Id = 812, CountryId = 63, DistrictName = "Harran" },
                 new District() { Id = 813, CountryId = 63, DistrictName = "Hilvan" },
                 new District() { Id = 814, CountryId = 63, DistrictName = "Siverek" },
                 new District() { Id = 815, CountryId = 63, DistrictName = "Suruç" },
                 new District() { Id = 816, CountryId = 63, DistrictName = "Viransehir" },
                 new District() { Id = 817, CountryId = 64, DistrictName = "Merkez" },
                 new District() { Id = 818, CountryId = 64, DistrictName = "Banaz" },
                 new District() { Id = 819, CountryId = 64, DistrictName = "Esme" },
                 new District() { Id = 820, CountryId = 64, DistrictName = "Karahalli" },
                 new District() { Id = 821, CountryId = 64, DistrictName = "Sivasli" },
                 new District() { Id = 822, CountryId = 64, DistrictName = "Ulubey" },
                 new District() { Id = 823, CountryId = 65, DistrictName = "Merkez" },
                 new District() { Id = 824, CountryId = 65, DistrictName = "Bahçesaray" },
                 new District() { Id = 825, CountryId = 65, DistrictName = "Baskale" },
                 new District() { Id = 826, CountryId = 65, DistrictName = "Çaldiran" },
                 new District() { Id = 827, CountryId = 65, DistrictName = "Çatak" },
                 new District() { Id = 828, CountryId = 65, DistrictName = "Edremit" },
                 new District() { Id = 829, CountryId = 65, DistrictName = "Ercis" },
                 new District() { Id = 830, CountryId = 65, DistrictName = "Gevas" },
                 new District() { Id = 831, CountryId = 65, DistrictName = "Gürpinar" },
                 new District() { Id = 832, CountryId = 65, DistrictName = "Muradiye" },
                 new District() { Id = 833, CountryId = 65, DistrictName = "Özalp" },
                 new District() { Id = 834, CountryId = 65, DistrictName = "Saray" },
                 new District() { Id = 835, CountryId = 66, DistrictName = "Merkez" },
                 new District() { Id = 836, CountryId = 66, DistrictName = "Akdagmadeni" },
                 new District() { Id = 837, CountryId = 66, DistrictName = "Aydincik" },
                 new District() { Id = 838, CountryId = 66, DistrictName = "Bogazliyan" },
                 new District() { Id = 839, CountryId = 66, DistrictName = "Çandir" },
                 new District() { Id = 840, CountryId = 66, DistrictName = "Çayiralan" },
                 new District() { Id = 841, CountryId = 66, DistrictName = "Çekerek" },
                 new District() { Id = 842, CountryId = 66, DistrictName = "Kadisehri" },
                 new District() { Id = 843, CountryId = 66, DistrictName = "Sarikaya" },
                 new District() { Id = 844, CountryId = 66, DistrictName = "Saraykent" },
                 new District() { Id = 845, CountryId = 66, DistrictName = "Sorgun" },
                 new District() { Id = 846, CountryId = 66, DistrictName = "Sefaatli" },
                 new District() { Id = 847, CountryId = 66, DistrictName = "Yenifakili" },
                 new District() { Id = 848, CountryId = 66, DistrictName = "Yerköy" },
                 new District() { Id = 849, CountryId = 67, DistrictName = "Merkez" },
                 new District() { Id = 850, CountryId = 67, DistrictName = "Alapli" },
                 new District() { Id = 851, CountryId = 67, DistrictName = "Çamoluk" },
                 new District() { Id = 852, CountryId = 67, DistrictName = "Çaycuma" },
                 new District() { Id = 853, CountryId = 67, DistrictName = "Devrek" },
                 new District() { Id = 854, CountryId = 67, DistrictName = "Eflani" },
                 new District() { Id = 855, CountryId = 67, DistrictName = "Eregli" },
                 new District() { Id = 856, CountryId = 67, DistrictName = "Gökçebey" },
                 new District() { Id = 857, CountryId = 68, DistrictName = "Merkez" },
                 new District() { Id = 858, CountryId = 68, DistrictName = "Agaçören" },
                 new District() { Id = 859, CountryId = 68, DistrictName = "Eskil" },
                 new District() { Id = 860, CountryId = 68, DistrictName = "Gülagaç" },
                 new District() { Id = 861, CountryId = 68, DistrictName = "Güzelyurt" },
                 new District() { Id = 862, CountryId = 68, DistrictName = "Ortaköy" },
                 new District() { Id = 863, CountryId = 68, DistrictName = "Sariyahsi" },
                 new District() { Id = 864, CountryId = 69, DistrictName = "Merkez" },
                 new District() { Id = 865, CountryId = 69, DistrictName = "Aydintepe" },
                 new District() { Id = 866, CountryId = 69, DistrictName = "Demirözü" },
                 new District() { Id = 867, CountryId = 70, DistrictName = "Merkez" },
                 new District() { Id = 868, CountryId = 70, DistrictName = "Ayranci" },
                 new District() { Id = 869, CountryId = 70, DistrictName = "Basyayla" },
                 new District() { Id = 870, CountryId = 70, DistrictName = "Ermenek" },
                 new District() { Id = 871, CountryId = 70, DistrictName = "Kazimkarabekir" },
                 new District() { Id = 872, CountryId = 70, DistrictName = "Sariveliler" },
                 new District() { Id = 873, CountryId = 71, DistrictName = "Merkez" },
                 new District() { Id = 874, CountryId = 71, DistrictName = "Bahsili" },
                 new District() { Id = 875, CountryId = 71, DistrictName = "Bagliseyh" },
                 new District() { Id = 876, CountryId = 71, DistrictName = "Çelebi" },
                 new District() { Id = 877, CountryId = 71, DistrictName = "Delice" },
                 new District() { Id = 878, CountryId = 71, DistrictName = "Karakeçili" },
                 new District() { Id = 879, CountryId = 71, DistrictName = "Keskin" },
                 new District() { Id = 880, CountryId = 71, DistrictName = "Sulakyurt" },
                 new District() { Id = 881, CountryId = 71, DistrictName = "Yahsihan" },
                 new District() { Id = 882, CountryId = 72, DistrictName = "Merkez" },
                 new District() { Id = 883, CountryId = 72, DistrictName = "Gercüs" },
                 new District() { Id = 884, CountryId = 72, DistrictName = "Hasankeyf" },
                 new District() { Id = 885, CountryId = 72, DistrictName = "Besiri" },
                 new District() { Id = 886, CountryId = 72, DistrictName = "Kozluk" },
                 new District() { Id = 887, CountryId = 72, DistrictName = "Sason" },
                 new District() { Id = 888, CountryId = 73, DistrictName = "Merkez" },
                 new District() { Id = 889, CountryId = 73, DistrictName = "Beytüsseba" },
                 new District() { Id = 890, CountryId = 73, DistrictName = "Uludere" },
                 new District() { Id = 891, CountryId = 73, DistrictName = "Cizre" },
                 new District() { Id = 892, CountryId = 73, DistrictName = "Idil" },
                 new District() { Id = 893, CountryId = 73, DistrictName = "Silopi" },
                 new District() { Id = 894, CountryId = 73, DistrictName = "Güçlükonak" },
                 new District() { Id = 895, CountryId = 74, DistrictName = "Merkez" },
                 new District() { Id = 896, CountryId = 74, DistrictName = "Amasra" },
                 new District() { Id = 897, CountryId = 74, DistrictName = "Kurucasile" },
                 new District() { Id = 898, CountryId = 74, DistrictName = "Ulus" },
                 new District() { Id = 899, CountryId = 75, DistrictName = "Merkez" },
                 new District() { Id = 900, CountryId = 75, DistrictName = "Çildir" },
                 new District() { Id = 901, CountryId = 75, DistrictName = "Damal" },
                 new District() { Id = 902, CountryId = 75, DistrictName = "Göle" },
                 new District() { Id = 903, CountryId = 75, DistrictName = "Hanak" },
                 new District() { Id = 904, CountryId = 75, DistrictName = "Posof" },
                 new District() { Id = 905, CountryId = 76, DistrictName = "Merkez" },
                 new District() { Id = 906, CountryId = 76, DistrictName = "Aralik" },
                 new District() { Id = 907, CountryId = 76, DistrictName = "Karakoyunlu" },
                 new District() { Id = 908, CountryId = 76, DistrictName = "Tuzluca" },
                 new District() { Id = 909, CountryId = 77, DistrictName = "Merkez" },
                 new District() { Id = 910, CountryId = 77, DistrictName = "Altinova" },
                 new District() { Id = 911, CountryId = 77, DistrictName = "Armutlu" },
                 new District() { Id = 912, CountryId = 77, DistrictName = "Cinarcik" },
                 new District() { Id = 913, CountryId = 77, DistrictName = "Ciftlikkoy" },
                 new District() { Id = 914, CountryId = 77, DistrictName = "Termal" },
                 new District() { Id = 915, CountryId = 78, DistrictName = "Merkez" },
                 new District() { Id = 916, CountryId = 78, DistrictName = "Eflani" },
                 new District() { Id = 917, CountryId = 78, DistrictName = "Eskipazar" },
                 new District() { Id = 918, CountryId = 78, DistrictName = "Ovacik" },
                 new District() { Id = 919, CountryId = 78, DistrictName = "Safranbolu" },
                 new District() { Id = 920, CountryId = 78, DistrictName = "Yenice" },
                 new District() { Id = 921, CountryId = 79, DistrictName = "Merkez" },
                 new District() { Id = 922, CountryId = 79, DistrictName = "Elbeyli" },
                 new District() { Id = 923, CountryId = 79, DistrictName = "Musabeyli" },
                 new District() { Id = 924, CountryId = 79, DistrictName = "Polateli" },
                 new District() { Id = 925, CountryId = 80, DistrictName = "Merkez" },
                 new District() { Id = 926, CountryId = 80, DistrictName = "Bahçe" },
                 new District() { Id = 927, CountryId = 80, DistrictName = "Hasanbeyli" },
                 new District() { Id = 928, CountryId = 80, DistrictName = "Düziçi" },
                 new District() { Id = 929, CountryId = 80, DistrictName = "Kadirli" },
                 new District() { Id = 930, CountryId = 80, DistrictName = "Sunbas" },
                 new District() { Id = 931, CountryId = 80, DistrictName = "Toprakkale" },
                 new District() { Id = 932, CountryId = 81, DistrictName = "Merkez" },
                 new District() { Id = 933, CountryId = 81, DistrictName = "Akçakoca" },
                 new District() { Id = 934, CountryId = 81, DistrictName = "Cumayeri" },
                 new District() { Id = 935, CountryId = 81, DistrictName = "Çilimli" },
                 new District() { Id = 936, CountryId = 81, DistrictName = "Gölyaka" },
                 new District() { Id = 937, CountryId = 81, DistrictName = "Gümüsova" },
                 new District() { Id = 938, CountryId = 81, DistrictName = "Kaynasli" },
                 new District() { Id = 939, CountryId = 81, DistrictName = "Yigilca" }





                );
        }


    }
}
